<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
	<ImplicitUsings>enable</ImplicitUsings>
	<RootNamespace>Infrastructure.Migrations</RootNamespace>
	<PublishAot>false</PublishAot>
	<PublishTrimmed>false</PublishTrimmed>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" />
  </ItemGroup>


  <ItemGroup>
    <ProjectReference Include="..\Citadel.Infrastructure\Citadel.Infrastructure.csproj" />
  </ItemGroup>


  <ItemGroup>
    <Folder Include="EntityFramework\" />
  </ItemGroup>

</Project>
