[package]
name = "citadel-resources"
version = "0.0.0"
edition.workspace = true
rust-version.workspace = true
publish = false

[dependencies]
citadel-git = { path = "../git" }
utoipa.workspace = true
base64.workspace = true
hmac.workspace = true
sha2.workspace = true
subtle.workspace = true
chrono.workspace = true
citadel-domain = { path = "../domain" }
futures-util.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
uuid.workspace = true
zeroize.workspace = true
