<Project>
  <PropertyGroup>
    <Version>1.0.0</Version>
    <AssemblyVersion>1.0.0</AssemblyVersion>
	<Copyright>Citadel © 2024. All rights reserved.</Copyright>
  </PropertyGroup>
	
	<PropertyGroup>
		<TargetFramework>net9.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<PublishTrimmed>true</PublishTrimmed>
		<InvariantGlobalization>true</InvariantGlobalization>
		<RepositoryType>git</RepositoryType>
		<PublishRepositoryUrl>true</PublishRepositoryUrl>
		<RepositoryUrl>https://github.com/Citadel-P/Citadel.Agent</RepositoryUrl>
	</PropertyGroup>

</Project>