<Project>
  <PropertyGroup>
    <Authors>Hammou Arras</Authors>
    <Copyright>Citadel ©, 2024 onwards</Copyright>
    <Description>Citadel API for managing platforms, containers, registries, images, networks, and volumes.</Description>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <PublishTrimmed>true</PublishTrimmed>
    <UseAppHost>true</UseAppHost>
    <InvariantGlobalization>true</InvariantGlobalization>
    <RepositoryType>git</RepositoryType>
    <PublishRepositoryUrl>true</PublishRepositoryUrl>
    <RepositoryUrl>https://github.com/Citadel-P/Citadel</RepositoryUrl>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>
	
	<ItemGroup Condition="'$(DOTNET_RUNNING_IN_CONTAINER)' != 'true'">
		<PackageReference Include="Nerdbank.GitVersioning" PrivateAssets="all" />
	</ItemGroup>
</Project>