FROM mcr.microsoft.com/dotnet/sdk:10.0-alpine
WORKDIR /app

# OS deps for dev tools
RUN apk add --no-cache \
    clang lld musl-dev libc6-compat \
    bash curl git

# Deps
COPY src/Citadel.Contracts/install-deps.sh .
COPY install-server-deps.sh .
RUN chmod +x install-deps.sh install-server-deps.sh \
    && ./install-deps.sh \
    && ./install-server-deps.sh \
    && rm install-deps.sh install-server-deps.sh

COPY src/Citadel.Contracts/starship.toml /root/.config/starship.toml
ENV STARSHIP_CONFIG=/root/.config/starship.toml

# Copy everything
WORKDIR /src
COPY . .

WORKDIR /src/src/Citadel.WebApi
EXPOSE 8000
EXPOSE 8001

CMD ["dotnet", "run", "--urls=http://0.0.0.0:8000"]
