services:
  citadel-server:
    image: ghcr.io/citadel-p/citadel:${CITADEL_IMAGE_TAG:-latest}
    restart: unless-stopped
    env_file: .env
    environment:
      ConnectionStrings__Postgres: "Host=${PG_HOST};Database=${PG_DATABASE};Username=${PG_USER};Password=${PG_PASSWORD}"
    depends_on:
      - postgres
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - citadel_data:/app/data
    ports:
      - "8000:8000" # API
      - "8001:8001" # Grpc

  postgres:
    image: postgres:alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_DATABASE}
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  citadel_data:
  postgres_data: