version: '3.4'

services:
  citadel:
    container_name: citadel
    image: ${DOCKER_REGISTRY-}citadelwebapi
    environment:
     - BusConfiguration__Hosts__0__Host=host.docker.internal
     - BusConfiguration__Hosts__0__Port=5672
     - BusConfiguration__Transport__Username=rabbituser
     - BusConfiguration__Transport__Password=r@bb1tPasS
     - ASPNETCORE_ENVIRONMENT=Development
    mem_limit: 400m
    build:
      context: .
      dockerfile: Citadel.WebApi/Dockerfile
    volumes:
      - citadel_data:/app/data
    networks:
      - citadel
    ports:
      - 8000:8080

volumes:
  citadel_data:

networks:
  citadel:
   name: citadel_network  