services:
  server:
    image: citadel.dev
    build:
      context: .
      dockerfile: src/Citadel.WebApi/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

  pg_db:
    ports:
      - "5432:5432" # Allows to use local DB tools during dev
