[package]
name = "citadel-tags"
version = "0.0.0"
edition.workspace = true
rust-version.workspace = true
publish = false

[dependencies]
citadel-primitives = { path = "../primitives" }
chrono.workspace = true
futures-util.workspace = true
serde.workspace = true
thiserror.workspace = true
uuid.workspace = true

[lints]
workspace = true
