[package]
name = "citadel-server"
version = "0.0.0"
edition.workspace = true
rust-version.workspace = true
publish = false

[dependencies]
axum.workspace = true
citadel-adapters = { path = "../adapters" }
citadel-application = { path = "../application" }
citadel-domain = { path = "../domain" }
clap.workspace = true
futures-util.workspace = true
reqwest.workspace = true
serde.workspace = true
serde_json.workspace = true
sqlx.workspace = true
thiserror.workspace = true
tokio.workspace = true
tokio-util.workspace = true
tower-http.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
url.workspace = true
uuid.workspace = true
