<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <ImplicitUsings>enable</ImplicitUsings>
	<RootNamespace>Domain</RootNamespace>
  </PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\Citadel.Contracts\Citadel.Hosting.Common\Citadel.Hosting.Common.csproj" />
	</ItemGroup>

</Project>
