FROM alpine@sha256:25109184c71bdad752c8312a8623239686a9a2071e8825f20acb8f2198c3f659 AS download

ARG ATLAS_VERSION=v1.3.0
ARG ATLAS_SHA256=10d7913e3dce43ab99b8d71534a4cbadaf11a16dc293adf3b91d10e83a0ac70b

RUN wget -q "https://release.ariga.io/atlas/atlas-community-linux-amd64-${ATLAS_VERSION}" -O /atlas \
    && echo "${ATLAS_SHA256}  /atlas" | sha256sum -c - \
    && chmod 0555 /atlas

FROM scratch
COPY --from=download /atlas /atlas
ENTRYPOINT ["/atlas"]
