// <auto-generated />
using System;
using Infrastructure.EntityFramework;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20241120230257_migration0001")]
    partial class migration0001
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("Infrastructure.Entities.ContainerInfo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ContainerId")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("Created")
                        .HasColumnType("TEXT");

                    b.Property<string>("Image")
                        .HasColumnType("TEXT");

                    b.Property<string>("Labels")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PlatformId")
                        .HasColumnType("TEXT");

                    b.Property<string>("State")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PlatformId");

                    b.ToTable("ContainersInfo", (string)null);
                });

            modelBuilder.Entity("Infrastructure.Entities.ContainerStat", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ContainerInfoId")
                        .HasColumnType("TEXT");

                    b.Property<double?>("CpuUsage")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<double?>("MemoryLimit")
                        .HasColumnType("REAL");

                    b.Property<double?>("MemoryUsage")
                        .HasColumnType("REAL");

                    b.Property<ulong?>("RxBytes")
                        .HasColumnType("INTEGER");

                    b.Property<ulong?>("TxBytes")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ContainerInfoId");

                    b.ToTable("ContainerStats", (string)null);
                });

            modelBuilder.Entity("Infrastructure.Entities.Identity.Permission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("PermissionCode")
                        .HasColumnType("INTEGER")
                        .HasColumnName("PermissionCode");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("Permissions", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("01934bd0-84ff-774b-b176-9c2bce6d3af4"),
                            PermissionCode = 1,
                            RoleId = new Guid("01934bd0-84fe-7abe-a03a-e2d9919bfa2d")
                        },
                        new
                        {
                            Id = new Guid("01934bd0-84ff-7119-a41f-3ed0e5719bac"),
                            PermissionCode = 2,
                            RoleId = new Guid("01934bd0-84fe-7abe-a03a-e2d9919bfa2d")
                        },
                        new
                        {
                            Id = new Guid("01934bd0-84ff-7f13-a311-ef4cfd942777"),
                            PermissionCode = 3,
                            RoleId = new Guid("01934bd0-84fe-7abe-a03a-e2d9919bfa2d")
                        },
                        new
                        {
                            Id = new Guid("01934bd0-84ff-76c2-8cb0-9bfe6625f1ba"),
                            PermissionCode = 4,
                            RoleId = new Guid("01934bd0-84fe-7abe-a03a-e2d9919bfa2d")
                        },
                        new
                        {
                            Id = new Guid("01934bd0-84ff-73e6-b3c6-f095b7d442f1"),
                            PermissionCode = 5,
                            RoleId = new Guid("01934bd0-84fe-7abe-a03a-e2d9919bfa2d")
                        },
                        new
                        {
                            Id = new Guid("01934bd0-84ff-746f-9d14-60ece28db8c7"),
                            PermissionCode = 6,
                            RoleId = new Guid("01934bd0-84fe-7abe-a03a-e2d9919bfa2d")
                        },
                        new
                        {
                            Id = new Guid("01934bd0-84ff-7433-a8c4-d18740b14abf"),
                            PermissionCode = 7,
                            RoleId = new Guid("01934bd0-84fe-7abe-a03a-e2d9919bfa2d")
                        },
                        new
                        {
                            Id = new Guid("01934bd0-84ff-799e-9a45-0655cbb0580c"),
                            PermissionCode = 8,
                            RoleId = new Guid("01934bd0-84fe-7abe-a03a-e2d9919bfa2d")
                        },
                        new
                        {
                            Id = new Guid("01934bd0-84ff-7461-b148-97c8da6dc960"),
                            PermissionCode = 9,
                            RoleId = new Guid("01934bd0-84fe-7abe-a03a-e2d9919bfa2d")
                        },
                        new
                        {
                            Id = new Guid("01934bd0-84ff-75e8-be36-d906e8141cd9"),
                            PermissionCode = 10,
                            RoleId = new Guid("01934bd0-84fe-7abe-a03a-e2d9919bfa2d")
                        },
                        new
                        {
                            Id = new Guid("01934bd0-84ff-7697-b581-0beb2a01a41e"),
                            PermissionCode = 11,
                            RoleId = new Guid("01934bd0-84fe-7abe-a03a-e2d9919bfa2d")
                        },
                        new
                        {
                            Id = new Guid("01934bd0-84ff-7565-85af-727e4ff31641"),
                            PermissionCode = 12,
                            RoleId = new Guid("01934bd0-84fe-7abe-a03a-e2d9919bfa2d")
                        },
                        new
                        {
                            Id = new Guid("01934bd0-84ff-736d-8195-19da8444e24a"),
                            PermissionCode = 13,
                            RoleId = new Guid("01934bd0-84fe-7abe-a03a-e2d9919bfa2d")
                        },
                        new
                        {
                            Id = new Guid("01934bd0-84ff-7dc8-9aa3-b6171441c3db"),
                            PermissionCode = 14,
                            RoleId = new Guid("01934bd0-84fe-7abe-a03a-e2d9919bfa2d")
                        },
                        new
                        {
                            Id = new Guid("01934bd0-84ff-7810-95a5-a786db9926bb"),
                            PermissionCode = 15,
                            RoleId = new Guid("01934bd0-84fe-7abe-a03a-e2d9919bfa2d")
                        },
                        new
                        {
                            Id = new Guid("01934bd0-84ff-7ce1-9f27-70fab0efe872"),
                            PermissionCode = 16,
                            RoleId = new Guid("01934bd0-84fe-7abe-a03a-e2d9919bfa2d")
                        },
                        new
                        {
                            Id = new Guid("01934bd0-84ff-7443-9bc4-d9d9add22b2e"),
                            PermissionCode = 17,
                            RoleId = new Guid("01934bd0-84fe-7abe-a03a-e2d9919bfa2d")
                        },
                        new
                        {
                            Id = new Guid("01934bd0-84ff-7818-8b53-b8fad16c2573"),
                            PermissionCode = 18,
                            RoleId = new Guid("01934bd0-84fe-7abe-a03a-e2d9919bfa2d")
                        },
                        new
                        {
                            Id = new Guid("01934bd0-84ff-75cc-8fd2-271909639e41"),
                            PermissionCode = 19,
                            RoleId = new Guid("01934bd0-84fe-7abe-a03a-e2d9919bfa2d")
                        },
                        new
                        {
                            Id = new Guid("01934bd0-84ff-705c-a010-f6976e6c46c9"),
                            PermissionCode = 20,
                            RoleId = new Guid("01934bd0-84fe-7abe-a03a-e2d9919bfa2d")
                        },
                        new
                        {
                            Id = new Guid("01934bd0-84ff-7dfd-803b-a6f0a02c15f9"),
                            PermissionCode = 21,
                            RoleId = new Guid("01934bd0-84fe-7abe-a03a-e2d9919bfa2d")
                        },
                        new
                        {
                            Id = new Guid("01934bd0-84ff-70cf-b826-2720d66ec960"),
                            PermissionCode = 22,
                            RoleId = new Guid("01934bd0-84fe-7abe-a03a-e2d9919bfa2d")
                        },
                        new
                        {
                            Id = new Guid("01934bd0-84ff-7450-a7d8-ceb0c1e4f7ce"),
                            PermissionCode = 23,
                            RoleId = new Guid("01934bd0-84fe-7abe-a03a-e2d9919bfa2d")
                        },
                        new
                        {
                            Id = new Guid("01934bd0-84ff-7038-83e2-dffb0a4a9ec3"),
                            PermissionCode = 24,
                            RoleId = new Guid("01934bd0-84fe-7abe-a03a-e2d9919bfa2d")
                        },
                        new
                        {
                            Id = new Guid("01934bd0-84ff-78cb-816e-afa8bb9627a6"),
                            PermissionCode = 25,
                            RoleId = new Guid("01934bd0-84fe-7abe-a03a-e2d9919bfa2d")
                        },
                        new
                        {
                            Id = new Guid("01934bd0-84ff-7fe1-9486-63c267475087"),
                            PermissionCode = 26,
                            RoleId = new Guid("01934bd0-84fe-7abe-a03a-e2d9919bfa2d")
                        },
                        new
                        {
                            Id = new Guid("01934bd0-84ff-7a26-bd12-a22388209e5d"),
                            PermissionCode = 27,
                            RoleId = new Guid("01934bd0-84fe-7abe-a03a-e2d9919bfa2d")
                        },
                        new
                        {
                            Id = new Guid("01934bd0-84ff-7ed8-9081-77e3b2a87392"),
                            PermissionCode = 28,
                            RoleId = new Guid("01934bd0-84fe-7abe-a03a-e2d9919bfa2d")
                        },
                        new
                        {
                            Id = new Guid("01934bd0-84ff-7d3d-ae46-c179701a14bb"),
                            PermissionCode = 1,
                            RoleId = new Guid("01934bd0-84ff-7a25-8b54-265589aeb00c")
                        },
                        new
                        {
                            Id = new Guid("01934bd0-84ff-7b0d-a6df-583de2db2068"),
                            PermissionCode = 5,
                            RoleId = new Guid("01934bd0-84ff-7a25-8b54-265589aeb00c")
                        },
                        new
                        {
                            Id = new Guid("01934bd0-84ff-76d1-963e-eaf6a087b10b"),
                            PermissionCode = 9,
                            RoleId = new Guid("01934bd0-84ff-7a25-8b54-265589aeb00c")
                        },
                        new
                        {
                            Id = new Guid("01934bd0-84ff-7386-b878-ec08a9e97da0"),
                            PermissionCode = 13,
                            RoleId = new Guid("01934bd0-84ff-7a25-8b54-265589aeb00c")
                        },
                        new
                        {
                            Id = new Guid("01934bd0-84ff-7755-8a82-3c293ea14e99"),
                            PermissionCode = 14,
                            RoleId = new Guid("01934bd0-84ff-7a25-8b54-265589aeb00c")
                        },
                        new
                        {
                            Id = new Guid("01934bd0-84ff-706d-9354-5c13c1796742"),
                            PermissionCode = 15,
                            RoleId = new Guid("01934bd0-84ff-7a25-8b54-265589aeb00c")
                        },
                        new
                        {
                            Id = new Guid("01934bd0-84ff-7e8c-b1e0-3a77a98ce822"),
                            PermissionCode = 16,
                            RoleId = new Guid("01934bd0-84ff-7a25-8b54-265589aeb00c")
                        },
                        new
                        {
                            Id = new Guid("01934bd0-84ff-7d4d-9cc9-e47d96169a5e"),
                            PermissionCode = 17,
                            RoleId = new Guid("01934bd0-84ff-7a25-8b54-265589aeb00c")
                        },
                        new
                        {
                            Id = new Guid("01934bd0-84ff-742a-a532-4f0e795a685f"),
                            PermissionCode = 18,
                            RoleId = new Guid("01934bd0-84ff-7a25-8b54-265589aeb00c")
                        },
                        new
                        {
                            Id = new Guid("01934bd0-84ff-7949-ac0e-a9fdbba5f8f6"),
                            PermissionCode = 19,
                            RoleId = new Guid("01934bd0-84ff-7a25-8b54-265589aeb00c")
                        },
                        new
                        {
                            Id = new Guid("01934bd0-84ff-7f76-89b2-bd38396a2c67"),
                            PermissionCode = 20,
                            RoleId = new Guid("01934bd0-84ff-7a25-8b54-265589aeb00c")
                        },
                        new
                        {
                            Id = new Guid("01934bd0-84ff-7b6e-b89a-77d3d3cc08bb"),
                            PermissionCode = 21,
                            RoleId = new Guid("01934bd0-84ff-7a25-8b54-265589aeb00c")
                        },
                        new
                        {
                            Id = new Guid("01934bd0-84ff-7d65-b32a-405fe79e936c"),
                            PermissionCode = 22,
                            RoleId = new Guid("01934bd0-84ff-7a25-8b54-265589aeb00c")
                        },
                        new
                        {
                            Id = new Guid("01934bd0-84ff-7f8e-acfa-250be43757cc"),
                            PermissionCode = 24,
                            RoleId = new Guid("01934bd0-84ff-7a25-8b54-265589aeb00c")
                        },
                        new
                        {
                            Id = new Guid("01934bd0-84ff-7b51-99de-118314688e8e"),
                            PermissionCode = 26,
                            RoleId = new Guid("01934bd0-84ff-7a25-8b54-265589aeb00c")
                        },
                        new
                        {
                            Id = new Guid("01934bd0-84ff-75f2-8341-d26eaef6e5a9"),
                            PermissionCode = 27,
                            RoleId = new Guid("01934bd0-84ff-7a25-8b54-265589aeb00c")
                        },
                        new
                        {
                            Id = new Guid("01934bd0-84ff-7f7a-95bb-e11717b20b65"),
                            PermissionCode = 28,
                            RoleId = new Guid("01934bd0-84ff-7a25-8b54-265589aeb00c")
                        },
                        new
                        {
                            Id = new Guid("01934bd0-84ff-7a73-a283-6c606edd2e0f"),
                            PermissionCode = 1,
                            RoleId = new Guid("01934bd0-84ff-7a0f-9030-3f9352a83511")
                        },
                        new
                        {
                            Id = new Guid("01934bd0-84ff-76b3-ac33-27c3ec8ec7a6"),
                            PermissionCode = 5,
                            RoleId = new Guid("01934bd0-84ff-7a0f-9030-3f9352a83511")
                        },
                        new
                        {
                            Id = new Guid("01934bd0-84ff-716e-ac32-ba8b700a140b"),
                            PermissionCode = 9,
                            RoleId = new Guid("01934bd0-84ff-7a0f-9030-3f9352a83511")
                        },
                        new
                        {
                            Id = new Guid("01934bd0-84ff-74ac-b533-5381345ccaf2"),
                            PermissionCode = 13,
                            RoleId = new Guid("01934bd0-84ff-7a0f-9030-3f9352a83511")
                        },
                        new
                        {
                            Id = new Guid("01934bd0-84ff-7bb7-8815-96c5df844155"),
                            PermissionCode = 17,
                            RoleId = new Guid("01934bd0-84ff-7a0f-9030-3f9352a83511")
                        },
                        new
                        {
                            Id = new Guid("01934bd0-84ff-7c4d-a8fc-f9e8a893dcb3"),
                            PermissionCode = 21,
                            RoleId = new Guid("01934bd0-84ff-7a0f-9030-3f9352a83511")
                        },
                        new
                        {
                            Id = new Guid("01934bd0-84ff-7235-a492-1a47a0c4161b"),
                            PermissionCode = 25,
                            RoleId = new Guid("01934bd0-84ff-7a0f-9030-3f9352a83511")
                        });
                });

            modelBuilder.Entity("Infrastructure.Entities.Identity.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue(new DateTime(2024, 11, 20, 23, 2, 57, 64, DateTimeKind.Utc).AddTicks(4541))
                        .HasColumnName("CreatedAt");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasColumnName("Name");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue(new DateTime(2024, 11, 20, 23, 2, 57, 65, DateTimeKind.Utc).AddTicks(8826))
                        .HasColumnName("UpdatedAt");

                    b.HasKey("Id");

                    b.ToTable("Roles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("01934bd0-84fe-7abe-a03a-e2d9919bfa2d"),
                            CreatedAt = new DateTime(2024, 11, 20, 23, 2, 57, 22, DateTimeKind.Utc).AddTicks(9950),
                            Name = "Administrator",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("01934bd0-84ff-7a25-8b54-265589aeb00c"),
                            CreatedAt = new DateTime(2024, 11, 20, 23, 2, 57, 23, DateTimeKind.Utc).AddTicks(315),
                            Name = "Developer",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("01934bd0-84ff-7a0f-9030-3f9352a83511"),
                            CreatedAt = new DateTime(2024, 11, 20, 23, 2, 57, 23, DateTimeKind.Utc).AddTicks(317),
                            Name = "QA",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("Infrastructure.Entities.Identity.Team", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("Teams", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("01934bd0-84ff-7a20-ae88-888f274c88a7"),
                            Name = "Admins",
                            RoleId = new Guid("01934bd0-84fe-7abe-a03a-e2d9919bfa2d")
                        },
                        new
                        {
                            Id = new Guid("01934bd0-84ff-7a01-a9b7-19a84c97c4f5"),
                            Name = "Devs",
                            RoleId = new Guid("01934bd0-84ff-7a25-8b54-265589aeb00c")
                        },
                        new
                        {
                            Id = new Guid("01934bd0-84ff-790e-98b6-d720d47ca01e"),
                            Name = "QA",
                            RoleId = new Guid("01934bd0-84ff-7a0f-9030-3f9352a83511")
                        });
                });

            modelBuilder.Entity("Infrastructure.Entities.Identity.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("Id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue(new DateTime(2024, 11, 20, 23, 2, 57, 84, DateTimeKind.Utc).AddTicks(906))
                        .HasColumnName("CreatedAt");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasColumnName("Email");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasColumnName("Name");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasColumnName("Password");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue(new DateTime(2024, 11, 20, 23, 2, 57, 84, DateTimeKind.Utc).AddTicks(1648))
                        .HasColumnName("UpdatedAt");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("EmailIndex");

                    b.ToTable("Users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("01934bd0-84ff-7a0b-b89e-57b1ec7b8db5"),
                            CreatedAt = new DateTime(2024, 11, 20, 23, 2, 57, 23, DateTimeKind.Utc).AddTicks(7516),
                            Email = "admin@admin.com",
                            Name = "admin",
                            Password = "+HRQtRdSCAW2Z+JxWK4bcNBaD05BooUjNoXDiorhBeLGycZ1",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("01934bd0-850c-7727-9ca7-862904d5b3b1"),
                            CreatedAt = new DateTime(2024, 11, 20, 23, 2, 57, 36, DateTimeKind.Utc).AddTicks(7790),
                            Email = "dev@dev.com",
                            Name = "dev",
                            Password = "Juv8e61mds1If1G7yC7jGoKkhTdO3daGy/6zhF12gW9lrkVz",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("01934bd0-8512-7776-8973-8797d0d8979f"),
                            CreatedAt = new DateTime(2024, 11, 20, 23, 2, 57, 42, DateTimeKind.Utc).AddTicks(1704),
                            Email = "qa@qa.com",
                            Name = "qa",
                            Password = "Wo2c8VG1ZFmAkHDwIQq3OoPRzJwLhjkJ0xcWwQO4IrXGN6sb",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("Infrastructure.Entities.Platform", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Address")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Address")
                        .IsUnique()
                        .HasDatabaseName("AddressIndex");

                    b.ToTable("Platforms", (string)null);
                });

            modelBuilder.Entity("Infrastructure.Entities.PlatformStat", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<double>("CpuUsage")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<double>("MemoryUsage")
                        .HasColumnType("REAL");

                    b.Property<Guid>("PlatformId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PlatformId");

                    b.ToTable("PlatformStats", (string)null);
                });

            modelBuilder.Entity("Infrastructure.Entities.Registry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Configuration")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Registries", (string)null);
                });

            modelBuilder.Entity("Infrastructure.Entities.SwarmInfo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("ControlAvailable")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Error")
                        .HasColumnType("TEXT");

                    b.Property<string>("LocalNodeState")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<long>("Managers")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NodeAddr")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("NodeID")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<long>("Nodes")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("SystemInfoId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SystemInfoId")
                        .IsUnique();

                    b.ToTable("SwarmsInfo", (string)null);
                });

            modelBuilder.Entity("Infrastructure.Entities.SwarmPeer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Addr")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("NodeID")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SwarmInfoId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SwarmInfoId");

                    b.ToTable("SwarmsPeer", (string)null);
                });

            modelBuilder.Entity("Infrastructure.Entities.SystemInfo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AgentVersion")
                        .HasColumnType("TEXT");

                    b.Property<string>("Architecture")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<long>("Containers")
                        .HasColumnType("INTEGER");

                    b.Property<long>("ContainersPaused")
                        .HasColumnType("INTEGER");

                    b.Property<long>("ContainersRunning")
                        .HasColumnType("INTEGER");

                    b.Property<long>("ContainersStopped")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DaemonId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Driver")
                        .HasColumnType("TEXT");

                    b.Property<long>("Images")
                        .HasColumnType("INTEGER");

                    b.Property<long>("MemTotal")
                        .HasColumnType("INTEGER");

                    b.Property<long>("NCPU")
                        .HasColumnType("INTEGER");

                    b.Property<short>("NetworksCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OSType")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("OSVersion")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("OperatingSystem")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PlatformId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ServerVersion")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<short>("VolumesCount")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PlatformId")
                        .IsUnique();

                    b.ToTable("SystemsInfo", (string)null);
                });

            modelBuilder.Entity("Infrastructure.EntityFramework.JoiningTables.UserTeam", b =>
                {
                    b.Property<Guid>("TeamId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("TeamId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("UsersTeams");

                    b.HasData(
                        new
                        {
                            TeamId = new Guid("01934bd0-84ff-7a20-ae88-888f274c88a7"),
                            UserId = new Guid("01934bd0-84ff-7a0b-b89e-57b1ec7b8db5")
                        },
                        new
                        {
                            TeamId = new Guid("01934bd0-84ff-7a01-a9b7-19a84c97c4f5"),
                            UserId = new Guid("01934bd0-850c-7727-9ca7-862904d5b3b1")
                        },
                        new
                        {
                            TeamId = new Guid("01934bd0-84ff-790e-98b6-d720d47ca01e"),
                            UserId = new Guid("01934bd0-8512-7776-8973-8797d0d8979f")
                        });
                });

            modelBuilder.Entity("Infrastructure.Entities.ContainerInfo", b =>
                {
                    b.HasOne("Infrastructure.Entities.Platform", "Platform")
                        .WithMany()
                        .HasForeignKey("PlatformId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsMany("Infrastructure.Entities.ContainerPort", "Ports", b1 =>
                        {
                            b1.Property<Guid>("ContainerInfoId")
                                .HasColumnType("TEXT");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAddOrUpdate()
                                .HasColumnType("INTEGER");

                            b1.Property<string>("IP")
                                .HasColumnType("TEXT");

                            b1.Property<ushort>("PrivatePort")
                                .HasColumnType("INTEGER");

                            b1.Property<ushort>("PublicPort")
                                .HasColumnType("INTEGER");

                            b1.HasKey("ContainerInfoId", "__synthesizedOrdinal");

                            b1.ToTable("ContainersInfo");

                            b1.ToJson("Ports");

                            b1.WithOwner()
                                .HasForeignKey("ContainerInfoId");
                        });

                    b.Navigation("Platform");

                    b.Navigation("Ports");
                });

            modelBuilder.Entity("Infrastructure.Entities.ContainerStat", b =>
                {
                    b.HasOne("Infrastructure.Entities.ContainerInfo", null)
                        .WithMany("Stats")
                        .HasForeignKey("ContainerInfoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Infrastructure.Entities.Identity.Permission", b =>
                {
                    b.HasOne("Infrastructure.Entities.Identity.Role", null)
                        .WithMany("Permissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Infrastructure.Entities.Identity.Team", b =>
                {
                    b.HasOne("Infrastructure.Entities.Identity.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Infrastructure.Entities.PlatformStat", b =>
                {
                    b.HasOne("Infrastructure.Entities.Platform", null)
                        .WithMany("Stats")
                        .HasForeignKey("PlatformId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Infrastructure.Entities.SwarmInfo", b =>
                {
                    b.HasOne("Infrastructure.Entities.SystemInfo", null)
                        .WithOne("SwarmInfo")
                        .HasForeignKey("Infrastructure.Entities.SwarmInfo", "SystemInfoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Infrastructure.Entities.SwarmPeer", b =>
                {
                    b.HasOne("Infrastructure.Entities.SwarmInfo", null)
                        .WithMany("RemoteManagers")
                        .HasForeignKey("SwarmInfoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Infrastructure.Entities.SystemInfo", b =>
                {
                    b.HasOne("Infrastructure.Entities.Platform", null)
                        .WithOne("SystemInfo")
                        .HasForeignKey("Infrastructure.Entities.SystemInfo", "PlatformId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Infrastructure.EntityFramework.JoiningTables.UserTeam", b =>
                {
                    b.HasOne("Infrastructure.Entities.Identity.Team", null)
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Infrastructure.Entities.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Infrastructure.Entities.ContainerInfo", b =>
                {
                    b.Navigation("Stats");
                });

            modelBuilder.Entity("Infrastructure.Entities.Identity.Role", b =>
                {
                    b.Navigation("Permissions");
                });

            modelBuilder.Entity("Infrastructure.Entities.Platform", b =>
                {
                    b.Navigation("Stats");

                    b.Navigation("SystemInfo");
                });

            modelBuilder.Entity("Infrastructure.Entities.SwarmInfo", b =>
                {
                    b.Navigation("RemoteManagers");
                });

            modelBuilder.Entity("Infrastructure.Entities.SystemInfo", b =>
                {
                    b.Navigation("SwarmInfo");
                });
#pragma warning restore 612, 618
        }
    }
}
