// <auto-generated />
using System;
using Infrastructure.EntityFramework;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20241130220355_migration0001")]
    partial class migration0001
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("Infrastructure.Entities.ContainerInfo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ContainerId")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<int>("Created")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Image")
                        .HasColumnType("TEXT");

                    b.Property<string>("Labels")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PlatformId")
                        .HasColumnType("TEXT");

                    b.Property<string>("State")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ContainerId")
                        .IsUnique();

                    b.HasIndex("PlatformId");

                    b.ToTable("ContainersInfo", (string)null);
                });

            modelBuilder.Entity("Infrastructure.Entities.ContainerStat", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ContainerInfoId")
                        .HasColumnType("TEXT");

                    b.Property<double?>("CpuUsage")
                        .HasColumnType("REAL");

                    b.Property<long>("Created")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("MemoryLimit")
                        .HasColumnType("REAL");

                    b.Property<double?>("MemoryUsage")
                        .HasColumnType("REAL");

                    b.Property<ulong?>("RxBytes")
                        .HasColumnType("INTEGER");

                    b.Property<ulong?>("TxBytes")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ContainerInfoId");

                    b.ToTable("ContainerStats", (string)null);
                });

            modelBuilder.Entity("Infrastructure.Entities.Identity.Permission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("PermissionCode")
                        .HasColumnType("INTEGER")
                        .HasColumnName("PermissionCode");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("Permissions", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("01937f1a-1018-7ffb-af8f-3fd6849983f6"),
                            PermissionCode = 1,
                            RoleId = new Guid("01937f1a-1018-7384-a380-83286832d06b")
                        },
                        new
                        {
                            Id = new Guid("01937f1a-1019-7bee-812c-700aba9dcd33"),
                            PermissionCode = 2,
                            RoleId = new Guid("01937f1a-1018-7384-a380-83286832d06b")
                        },
                        new
                        {
                            Id = new Guid("01937f1a-1019-701b-9451-979979ade515"),
                            PermissionCode = 3,
                            RoleId = new Guid("01937f1a-1018-7384-a380-83286832d06b")
                        },
                        new
                        {
                            Id = new Guid("01937f1a-1019-7820-9de1-982f11bb5992"),
                            PermissionCode = 4,
                            RoleId = new Guid("01937f1a-1018-7384-a380-83286832d06b")
                        },
                        new
                        {
                            Id = new Guid("01937f1a-1019-7601-999d-c8fe39bd7abe"),
                            PermissionCode = 5,
                            RoleId = new Guid("01937f1a-1018-7384-a380-83286832d06b")
                        },
                        new
                        {
                            Id = new Guid("01937f1a-1019-7910-b324-6e8573002284"),
                            PermissionCode = 6,
                            RoleId = new Guid("01937f1a-1018-7384-a380-83286832d06b")
                        },
                        new
                        {
                            Id = new Guid("01937f1a-1019-78b2-a7f6-9898494b87d5"),
                            PermissionCode = 7,
                            RoleId = new Guid("01937f1a-1018-7384-a380-83286832d06b")
                        },
                        new
                        {
                            Id = new Guid("01937f1a-1019-7610-9d0f-d95884aa3375"),
                            PermissionCode = 8,
                            RoleId = new Guid("01937f1a-1018-7384-a380-83286832d06b")
                        },
                        new
                        {
                            Id = new Guid("01937f1a-1019-7d3e-91eb-624371da1b3c"),
                            PermissionCode = 9,
                            RoleId = new Guid("01937f1a-1018-7384-a380-83286832d06b")
                        },
                        new
                        {
                            Id = new Guid("01937f1a-1019-781d-93be-10c779863841"),
                            PermissionCode = 10,
                            RoleId = new Guid("01937f1a-1018-7384-a380-83286832d06b")
                        },
                        new
                        {
                            Id = new Guid("01937f1a-1019-7bc6-b9f9-02fd86b22dcc"),
                            PermissionCode = 11,
                            RoleId = new Guid("01937f1a-1018-7384-a380-83286832d06b")
                        },
                        new
                        {
                            Id = new Guid("01937f1a-1019-7f72-8109-993b4408fe17"),
                            PermissionCode = 12,
                            RoleId = new Guid("01937f1a-1018-7384-a380-83286832d06b")
                        },
                        new
                        {
                            Id = new Guid("01937f1a-1019-77bc-8c05-a4a529fb7508"),
                            PermissionCode = 13,
                            RoleId = new Guid("01937f1a-1018-7384-a380-83286832d06b")
                        },
                        new
                        {
                            Id = new Guid("01937f1a-1019-78db-b5b2-3abdf4fe6c1b"),
                            PermissionCode = 14,
                            RoleId = new Guid("01937f1a-1018-7384-a380-83286832d06b")
                        },
                        new
                        {
                            Id = new Guid("01937f1a-1019-77fa-8023-9feec44c259c"),
                            PermissionCode = 15,
                            RoleId = new Guid("01937f1a-1018-7384-a380-83286832d06b")
                        },
                        new
                        {
                            Id = new Guid("01937f1a-1019-7dea-885f-8bf719dcd194"),
                            PermissionCode = 16,
                            RoleId = new Guid("01937f1a-1018-7384-a380-83286832d06b")
                        },
                        new
                        {
                            Id = new Guid("01937f1a-1019-765d-a377-1de6ec3549d8"),
                            PermissionCode = 17,
                            RoleId = new Guid("01937f1a-1018-7384-a380-83286832d06b")
                        },
                        new
                        {
                            Id = new Guid("01937f1a-1019-74d3-9841-374159192566"),
                            PermissionCode = 18,
                            RoleId = new Guid("01937f1a-1018-7384-a380-83286832d06b")
                        },
                        new
                        {
                            Id = new Guid("01937f1a-1019-7eb7-b2a6-d39b4bcabc16"),
                            PermissionCode = 19,
                            RoleId = new Guid("01937f1a-1018-7384-a380-83286832d06b")
                        },
                        new
                        {
                            Id = new Guid("01937f1a-1019-75ab-8527-038bf0be0a2e"),
                            PermissionCode = 20,
                            RoleId = new Guid("01937f1a-1018-7384-a380-83286832d06b")
                        },
                        new
                        {
                            Id = new Guid("01937f1a-1019-73c5-93b5-f6b4025d9179"),
                            PermissionCode = 21,
                            RoleId = new Guid("01937f1a-1018-7384-a380-83286832d06b")
                        },
                        new
                        {
                            Id = new Guid("01937f1a-1019-7db5-83c3-37dacfa7a7bd"),
                            PermissionCode = 22,
                            RoleId = new Guid("01937f1a-1018-7384-a380-83286832d06b")
                        },
                        new
                        {
                            Id = new Guid("01937f1a-1019-7e4f-9eb3-3431898c12c5"),
                            PermissionCode = 23,
                            RoleId = new Guid("01937f1a-1018-7384-a380-83286832d06b")
                        },
                        new
                        {
                            Id = new Guid("01937f1a-1019-791b-97d7-573141cab081"),
                            PermissionCode = 24,
                            RoleId = new Guid("01937f1a-1018-7384-a380-83286832d06b")
                        },
                        new
                        {
                            Id = new Guid("01937f1a-1019-7840-9346-f6f57f40ab01"),
                            PermissionCode = 25,
                            RoleId = new Guid("01937f1a-1018-7384-a380-83286832d06b")
                        },
                        new
                        {
                            Id = new Guid("01937f1a-1019-7123-95b7-3014de7882ea"),
                            PermissionCode = 26,
                            RoleId = new Guid("01937f1a-1018-7384-a380-83286832d06b")
                        },
                        new
                        {
                            Id = new Guid("01937f1a-1019-7f26-81d4-762e0a7e88ad"),
                            PermissionCode = 27,
                            RoleId = new Guid("01937f1a-1018-7384-a380-83286832d06b")
                        },
                        new
                        {
                            Id = new Guid("01937f1a-1019-7a5d-9ba3-3f8b91b627f5"),
                            PermissionCode = 28,
                            RoleId = new Guid("01937f1a-1018-7384-a380-83286832d06b")
                        },
                        new
                        {
                            Id = new Guid("01937f1a-1019-72c7-9755-96a03a9eafb5"),
                            PermissionCode = 1,
                            RoleId = new Guid("01937f1a-1018-777c-bc3d-672acab83347")
                        },
                        new
                        {
                            Id = new Guid("01937f1a-1019-76f7-816f-cf8b049107e7"),
                            PermissionCode = 5,
                            RoleId = new Guid("01937f1a-1018-777c-bc3d-672acab83347")
                        },
                        new
                        {
                            Id = new Guid("01937f1a-1019-7d2f-b820-fa6108206797"),
                            PermissionCode = 9,
                            RoleId = new Guid("01937f1a-1018-777c-bc3d-672acab83347")
                        },
                        new
                        {
                            Id = new Guid("01937f1a-1019-79aa-8637-c2d20cbd7494"),
                            PermissionCode = 13,
                            RoleId = new Guid("01937f1a-1018-777c-bc3d-672acab83347")
                        },
                        new
                        {
                            Id = new Guid("01937f1a-1019-732d-87b7-2d1686c629cc"),
                            PermissionCode = 14,
                            RoleId = new Guid("01937f1a-1018-777c-bc3d-672acab83347")
                        },
                        new
                        {
                            Id = new Guid("01937f1a-1019-7628-9e51-7cab8f3172ce"),
                            PermissionCode = 15,
                            RoleId = new Guid("01937f1a-1018-777c-bc3d-672acab83347")
                        },
                        new
                        {
                            Id = new Guid("01937f1a-1019-7dcc-8594-eff75babb19b"),
                            PermissionCode = 16,
                            RoleId = new Guid("01937f1a-1018-777c-bc3d-672acab83347")
                        },
                        new
                        {
                            Id = new Guid("01937f1a-1019-77bd-bfbf-5f5f31a80669"),
                            PermissionCode = 17,
                            RoleId = new Guid("01937f1a-1018-777c-bc3d-672acab83347")
                        },
                        new
                        {
                            Id = new Guid("01937f1a-1019-7482-916a-13634db08665"),
                            PermissionCode = 18,
                            RoleId = new Guid("01937f1a-1018-777c-bc3d-672acab83347")
                        },
                        new
                        {
                            Id = new Guid("01937f1a-1019-7ad5-9b03-59f3f1e27d9a"),
                            PermissionCode = 19,
                            RoleId = new Guid("01937f1a-1018-777c-bc3d-672acab83347")
                        },
                        new
                        {
                            Id = new Guid("01937f1a-1019-7793-9f0d-019ae6f3a4ac"),
                            PermissionCode = 20,
                            RoleId = new Guid("01937f1a-1018-777c-bc3d-672acab83347")
                        },
                        new
                        {
                            Id = new Guid("01937f1a-1019-7695-9fb5-f3706adc71ed"),
                            PermissionCode = 21,
                            RoleId = new Guid("01937f1a-1018-777c-bc3d-672acab83347")
                        },
                        new
                        {
                            Id = new Guid("01937f1a-1019-7476-8313-6e7126699047"),
                            PermissionCode = 22,
                            RoleId = new Guid("01937f1a-1018-777c-bc3d-672acab83347")
                        },
                        new
                        {
                            Id = new Guid("01937f1a-1019-78b9-b284-c4b9da2ca9b6"),
                            PermissionCode = 24,
                            RoleId = new Guid("01937f1a-1018-777c-bc3d-672acab83347")
                        },
                        new
                        {
                            Id = new Guid("01937f1a-1019-7594-91af-f5cd1549434f"),
                            PermissionCode = 26,
                            RoleId = new Guid("01937f1a-1018-777c-bc3d-672acab83347")
                        },
                        new
                        {
                            Id = new Guid("01937f1a-1019-76d8-8adc-1d01d56544df"),
                            PermissionCode = 27,
                            RoleId = new Guid("01937f1a-1018-777c-bc3d-672acab83347")
                        },
                        new
                        {
                            Id = new Guid("01937f1a-1019-7c84-9dc0-fc57d181ddb2"),
                            PermissionCode = 28,
                            RoleId = new Guid("01937f1a-1018-777c-bc3d-672acab83347")
                        },
                        new
                        {
                            Id = new Guid("01937f1a-1019-7697-91ae-b53def3ba90f"),
                            PermissionCode = 1,
                            RoleId = new Guid("01937f1a-1018-74c9-bff3-21486353e14b")
                        },
                        new
                        {
                            Id = new Guid("01937f1a-1019-72be-b914-31af0fedf03e"),
                            PermissionCode = 5,
                            RoleId = new Guid("01937f1a-1018-74c9-bff3-21486353e14b")
                        },
                        new
                        {
                            Id = new Guid("01937f1a-1019-76b1-a4b0-202aed8ecd48"),
                            PermissionCode = 9,
                            RoleId = new Guid("01937f1a-1018-74c9-bff3-21486353e14b")
                        },
                        new
                        {
                            Id = new Guid("01937f1a-1019-7c57-8cd8-947384bcffb2"),
                            PermissionCode = 13,
                            RoleId = new Guid("01937f1a-1018-74c9-bff3-21486353e14b")
                        },
                        new
                        {
                            Id = new Guid("01937f1a-1019-74fc-86c0-6f664b89c4d6"),
                            PermissionCode = 17,
                            RoleId = new Guid("01937f1a-1018-74c9-bff3-21486353e14b")
                        },
                        new
                        {
                            Id = new Guid("01937f1a-1019-7c48-9556-85ebd15d7ed6"),
                            PermissionCode = 21,
                            RoleId = new Guid("01937f1a-1018-74c9-bff3-21486353e14b")
                        },
                        new
                        {
                            Id = new Guid("01937f1a-1019-7fb0-877d-d247e79f1381"),
                            PermissionCode = 25,
                            RoleId = new Guid("01937f1a-1018-74c9-bff3-21486353e14b")
                        });
                });

            modelBuilder.Entity("Infrastructure.Entities.Identity.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue(new DateTime(2024, 11, 30, 22, 3, 54, 813, DateTimeKind.Utc).AddTicks(6845))
                        .HasColumnName("CreatedAt");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasColumnName("Name");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue(new DateTime(2024, 11, 30, 22, 3, 54, 815, DateTimeKind.Utc).AddTicks(587))
                        .HasColumnName("UpdatedAt");

                    b.HasKey("Id");

                    b.ToTable("Roles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("01937f1a-1018-7384-a380-83286832d06b"),
                            CreatedAt = new DateTime(2024, 11, 30, 22, 3, 54, 776, DateTimeKind.Utc).AddTicks(8262),
                            Name = "Administrator",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("01937f1a-1018-777c-bc3d-672acab83347"),
                            CreatedAt = new DateTime(2024, 11, 30, 22, 3, 54, 776, DateTimeKind.Utc).AddTicks(8522),
                            Name = "Developer",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("01937f1a-1018-74c9-bff3-21486353e14b"),
                            CreatedAt = new DateTime(2024, 11, 30, 22, 3, 54, 776, DateTimeKind.Utc).AddTicks(8524),
                            Name = "QA",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("Infrastructure.Entities.Identity.Team", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("Teams", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("01937f1a-1019-76c5-8851-be3dba2306d4"),
                            Name = "Admins",
                            RoleId = new Guid("01937f1a-1018-7384-a380-83286832d06b")
                        },
                        new
                        {
                            Id = new Guid("01937f1a-1019-7df8-a365-5ead27a06491"),
                            Name = "Devs",
                            RoleId = new Guid("01937f1a-1018-777c-bc3d-672acab83347")
                        },
                        new
                        {
                            Id = new Guid("01937f1a-1019-750b-aa8d-880f29f3aff0"),
                            Name = "QA",
                            RoleId = new Guid("01937f1a-1018-74c9-bff3-21486353e14b")
                        });
                });

            modelBuilder.Entity("Infrastructure.Entities.Identity.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("Id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue(new DateTime(2024, 11, 30, 22, 3, 54, 830, DateTimeKind.Utc).AddTicks(4772))
                        .HasColumnName("CreatedAt");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasColumnName("Email");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasColumnName("Name");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasColumnName("Password");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue(new DateTime(2024, 11, 30, 22, 3, 54, 830, DateTimeKind.Utc).AddTicks(5508))
                        .HasColumnName("UpdatedAt");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("EmailIndex");

                    b.ToTable("Users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("01937f1a-1019-7964-9bad-83de9b370a7c"),
                            CreatedAt = new DateTime(2024, 11, 30, 22, 3, 54, 777, DateTimeKind.Utc).AddTicks(4279),
                            Email = "admin@admin.com",
                            Name = "admin",
                            Password = "sxXMX2aY6Obc2ZvZofa3DFlDjqd/P7qzYrhAoMhUZFEugmH2",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("01937f1a-1024-7282-af3b-5ab0994c5e14"),
                            CreatedAt = new DateTime(2024, 11, 30, 22, 3, 54, 788, DateTimeKind.Utc).AddTicks(6357),
                            Email = "dev@dev.com",
                            Name = "dev",
                            Password = "lBfctv6K1XlYlbEvyT7dlTGx4sPUM7DGaAD3HPmUAYjD/jTO",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("01937f1a-1029-7659-8cb5-bd29715ed99b"),
                            CreatedAt = new DateTime(2024, 11, 30, 22, 3, 54, 793, DateTimeKind.Utc).AddTicks(7191),
                            Email = "qa@qa.com",
                            Name = "qa",
                            Password = "QPLDVMTGOn/n1n32S8mi+Ho4HNs8UnRERbiCSQGZQpfJ/1As",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("Infrastructure.Entities.Platform", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Address")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Address")
                        .IsUnique()
                        .HasDatabaseName("AddressIndex");

                    b.ToTable("Platforms", (string)null);
                });

            modelBuilder.Entity("Infrastructure.Entities.PlatformStat", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<double>("CpuUsage")
                        .HasColumnType("REAL");

                    b.Property<long>("Created")
                        .HasColumnType("INTEGER");

                    b.Property<double>("MemoryUsage")
                        .HasColumnType("REAL");

                    b.Property<Guid>("PlatformId")
                        .HasColumnType("TEXT");

                    b.Property<double>("RxBytes")
                        .HasColumnType("REAL");

                    b.Property<double>("TxBytes")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("Created")
                        .IsUnique();

                    b.HasIndex("PlatformId");

                    b.ToTable("PlatformStats", (string)null);
                });

            modelBuilder.Entity("Infrastructure.Entities.Registry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Configuration")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Registries", (string)null);
                });

            modelBuilder.Entity("Infrastructure.Entities.SwarmInfo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("ControlAvailable")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Error")
                        .HasColumnType("TEXT");

                    b.Property<string>("LocalNodeState")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<long>("Managers")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NodeAddr")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("NodeID")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<long>("Nodes")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("SystemInfoId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SystemInfoId")
                        .IsUnique();

                    b.ToTable("SwarmsInfo", (string)null);
                });

            modelBuilder.Entity("Infrastructure.Entities.SwarmPeer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Addr")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("NodeID")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SwarmInfoId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SwarmInfoId");

                    b.ToTable("SwarmsPeer", (string)null);
                });

            modelBuilder.Entity("Infrastructure.Entities.SystemInfo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AgentVersion")
                        .HasColumnType("TEXT");

                    b.Property<string>("Architecture")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<long>("Containers")
                        .HasColumnType("INTEGER");

                    b.Property<long>("ContainersPaused")
                        .HasColumnType("INTEGER");

                    b.Property<long>("ContainersRunning")
                        .HasColumnType("INTEGER");

                    b.Property<long>("ContainersStopped")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DaemonId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Driver")
                        .HasColumnType("TEXT");

                    b.Property<long>("Images")
                        .HasColumnType("INTEGER");

                    b.Property<long>("MemTotal")
                        .HasColumnType("INTEGER");

                    b.Property<long>("Ncpu")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NetworksCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OperatingSystem")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("OsType")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("OsVersion")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PlatformId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ServerVersion")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<int>("VolumesCount")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PlatformId")
                        .IsUnique();

                    b.ToTable("SystemsInfo", (string)null);
                });

            modelBuilder.Entity("Infrastructure.EntityFramework.JoiningTables.UserTeam", b =>
                {
                    b.Property<Guid>("TeamId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("TeamId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("UsersTeams");

                    b.HasData(
                        new
                        {
                            TeamId = new Guid("01937f1a-1019-76c5-8851-be3dba2306d4"),
                            UserId = new Guid("01937f1a-1019-7964-9bad-83de9b370a7c")
                        },
                        new
                        {
                            TeamId = new Guid("01937f1a-1019-7df8-a365-5ead27a06491"),
                            UserId = new Guid("01937f1a-1024-7282-af3b-5ab0994c5e14")
                        },
                        new
                        {
                            TeamId = new Guid("01937f1a-1019-750b-aa8d-880f29f3aff0"),
                            UserId = new Guid("01937f1a-1029-7659-8cb5-bd29715ed99b")
                        });
                });

            modelBuilder.Entity("Infrastructure.Entities.ContainerInfo", b =>
                {
                    b.HasOne("Infrastructure.Entities.Platform", "Platform")
                        .WithMany()
                        .HasForeignKey("PlatformId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsMany("Infrastructure.Entities.ContainerPort", "Ports", b1 =>
                        {
                            b1.Property<Guid>("ContainerInfoId")
                                .HasColumnType("TEXT");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAddOrUpdate()
                                .HasColumnType("INTEGER");

                            b1.Property<string>("IP")
                                .HasColumnType("TEXT");

                            b1.Property<ushort>("PrivatePort")
                                .HasColumnType("INTEGER");

                            b1.Property<ushort>("PublicPort")
                                .HasColumnType("INTEGER");

                            b1.HasKey("ContainerInfoId", "__synthesizedOrdinal");

                            b1.ToTable("ContainersInfo");

                            b1.ToJson("Ports");

                            b1.WithOwner()
                                .HasForeignKey("ContainerInfoId");
                        });

                    b.Navigation("Platform");

                    b.Navigation("Ports");
                });

            modelBuilder.Entity("Infrastructure.Entities.ContainerStat", b =>
                {
                    b.HasOne("Infrastructure.Entities.ContainerInfo", null)
                        .WithMany("Stats")
                        .HasForeignKey("ContainerInfoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Infrastructure.Entities.Identity.Permission", b =>
                {
                    b.HasOne("Infrastructure.Entities.Identity.Role", null)
                        .WithMany("Permissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Infrastructure.Entities.Identity.Team", b =>
                {
                    b.HasOne("Infrastructure.Entities.Identity.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Infrastructure.Entities.PlatformStat", b =>
                {
                    b.HasOne("Infrastructure.Entities.Platform", null)
                        .WithMany("Stats")
                        .HasForeignKey("PlatformId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Infrastructure.Entities.SwarmInfo", b =>
                {
                    b.HasOne("Infrastructure.Entities.SystemInfo", "SystemInfo")
                        .WithOne("SwarmInfo")
                        .HasForeignKey("Infrastructure.Entities.SwarmInfo", "SystemInfoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SystemInfo");
                });

            modelBuilder.Entity("Infrastructure.Entities.SwarmPeer", b =>
                {
                    b.HasOne("Infrastructure.Entities.SwarmInfo", "SwarmInfo")
                        .WithMany("RemoteManagers")
                        .HasForeignKey("SwarmInfoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SwarmInfo");
                });

            modelBuilder.Entity("Infrastructure.Entities.SystemInfo", b =>
                {
                    b.HasOne("Infrastructure.Entities.Platform", "Platform")
                        .WithOne("SystemInfo")
                        .HasForeignKey("Infrastructure.Entities.SystemInfo", "PlatformId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Platform");
                });

            modelBuilder.Entity("Infrastructure.EntityFramework.JoiningTables.UserTeam", b =>
                {
                    b.HasOne("Infrastructure.Entities.Identity.Team", null)
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Infrastructure.Entities.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Infrastructure.Entities.ContainerInfo", b =>
                {
                    b.Navigation("Stats");
                });

            modelBuilder.Entity("Infrastructure.Entities.Identity.Role", b =>
                {
                    b.Navigation("Permissions");
                });

            modelBuilder.Entity("Infrastructure.Entities.Platform", b =>
                {
                    b.Navigation("Stats");

                    b.Navigation("SystemInfo");
                });

            modelBuilder.Entity("Infrastructure.Entities.SwarmInfo", b =>
                {
                    b.Navigation("RemoteManagers");
                });

            modelBuilder.Entity("Infrastructure.Entities.SystemInfo", b =>
                {
                    b.Navigation("SwarmInfo");
                });
#pragma warning restore 612, 618
        }
    }
}
