// <auto-generated />
using System;
using Infrastructure.EntityFramework;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250210235017_migration0001")]
    partial class migration0001
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.1");

            modelBuilder.Entity("Infrastructure.Entities.ContainerInfo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ContainerId")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<long>("Created")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Image")
                        .HasColumnType("TEXT");

                    b.Property<string>("Labels")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PlatformId")
                        .HasColumnType("TEXT");

                    b.Property<string>("State")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ContainerId")
                        .IsUnique();

                    b.HasIndex("PlatformId");

                    b.ToTable("ContainersInfo", (string)null);
                });

            modelBuilder.Entity("Infrastructure.Entities.ContainerStat", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ContainerInfoId")
                        .HasColumnType("TEXT");

                    b.Property<double?>("CpuUsage")
                        .HasColumnType("REAL");

                    b.Property<long>("Created")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("MemoryLimit")
                        .HasColumnType("REAL");

                    b.Property<double?>("MemoryUsage")
                        .HasColumnType("REAL");

                    b.Property<long?>("RxBytes")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("TxBytes")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ContainerInfoId");

                    b.ToTable("ContainerStats", (string)null);
                });

            modelBuilder.Entity("Infrastructure.Entities.Identity.Permission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("PermissionCode")
                        .HasColumnType("INTEGER")
                        .HasColumnName("PermissionCode");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("Permissions", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("0194f245-5105-7084-b56c-87ca341b6c5c"),
                            PermissionCode = 1,
                            RoleId = new Guid("0194f245-5105-78f5-8a31-ae761f22c91a")
                        },
                        new
                        {
                            Id = new Guid("0194f245-5105-7037-b5aa-89800f6a22da"),
                            PermissionCode = 2,
                            RoleId = new Guid("0194f245-5105-78f5-8a31-ae761f22c91a")
                        },
                        new
                        {
                            Id = new Guid("0194f245-5105-7f26-beb4-0989e7e44a97"),
                            PermissionCode = 3,
                            RoleId = new Guid("0194f245-5105-78f5-8a31-ae761f22c91a")
                        },
                        new
                        {
                            Id = new Guid("0194f245-5105-7060-be70-1f31f4b4dbde"),
                            PermissionCode = 4,
                            RoleId = new Guid("0194f245-5105-78f5-8a31-ae761f22c91a")
                        },
                        new
                        {
                            Id = new Guid("0194f245-5105-7f0c-927d-46f543fbaa3f"),
                            PermissionCode = 5,
                            RoleId = new Guid("0194f245-5105-78f5-8a31-ae761f22c91a")
                        },
                        new
                        {
                            Id = new Guid("0194f245-5105-73d6-a249-61ad258287b8"),
                            PermissionCode = 6,
                            RoleId = new Guid("0194f245-5105-78f5-8a31-ae761f22c91a")
                        },
                        new
                        {
                            Id = new Guid("0194f245-5105-7677-b28a-f6059916cb8e"),
                            PermissionCode = 7,
                            RoleId = new Guid("0194f245-5105-78f5-8a31-ae761f22c91a")
                        },
                        new
                        {
                            Id = new Guid("0194f245-5105-7af2-a3b8-d11db798bb25"),
                            PermissionCode = 8,
                            RoleId = new Guid("0194f245-5105-78f5-8a31-ae761f22c91a")
                        },
                        new
                        {
                            Id = new Guid("0194f245-5105-737e-b4c7-3252f09563e8"),
                            PermissionCode = 9,
                            RoleId = new Guid("0194f245-5105-78f5-8a31-ae761f22c91a")
                        },
                        new
                        {
                            Id = new Guid("0194f245-5105-752a-bb1e-3c46898d8f3c"),
                            PermissionCode = 10,
                            RoleId = new Guid("0194f245-5105-78f5-8a31-ae761f22c91a")
                        },
                        new
                        {
                            Id = new Guid("0194f245-5105-76c0-bdb0-c25e2db31bbe"),
                            PermissionCode = 11,
                            RoleId = new Guid("0194f245-5105-78f5-8a31-ae761f22c91a")
                        },
                        new
                        {
                            Id = new Guid("0194f245-5105-7bcc-afc2-c4fc3e415e94"),
                            PermissionCode = 12,
                            RoleId = new Guid("0194f245-5105-78f5-8a31-ae761f22c91a")
                        },
                        new
                        {
                            Id = new Guid("0194f245-5105-76c4-8093-ac3c8e386848"),
                            PermissionCode = 13,
                            RoleId = new Guid("0194f245-5105-78f5-8a31-ae761f22c91a")
                        },
                        new
                        {
                            Id = new Guid("0194f245-5105-70d3-a2d3-9a50fff38548"),
                            PermissionCode = 14,
                            RoleId = new Guid("0194f245-5105-78f5-8a31-ae761f22c91a")
                        },
                        new
                        {
                            Id = new Guid("0194f245-5105-7c69-ac75-2f8254e981ff"),
                            PermissionCode = 15,
                            RoleId = new Guid("0194f245-5105-78f5-8a31-ae761f22c91a")
                        },
                        new
                        {
                            Id = new Guid("0194f245-5105-755a-ab1b-7fefd6df4d66"),
                            PermissionCode = 16,
                            RoleId = new Guid("0194f245-5105-78f5-8a31-ae761f22c91a")
                        },
                        new
                        {
                            Id = new Guid("0194f245-5105-780e-ae6b-c58000f3d032"),
                            PermissionCode = 17,
                            RoleId = new Guid("0194f245-5105-78f5-8a31-ae761f22c91a")
                        },
                        new
                        {
                            Id = new Guid("0194f245-5105-7246-908d-ce248e9af211"),
                            PermissionCode = 18,
                            RoleId = new Guid("0194f245-5105-78f5-8a31-ae761f22c91a")
                        },
                        new
                        {
                            Id = new Guid("0194f245-5105-7030-adbb-e066f59fc27f"),
                            PermissionCode = 19,
                            RoleId = new Guid("0194f245-5105-78f5-8a31-ae761f22c91a")
                        },
                        new
                        {
                            Id = new Guid("0194f245-5105-78ec-b52c-7386cd06f67d"),
                            PermissionCode = 20,
                            RoleId = new Guid("0194f245-5105-78f5-8a31-ae761f22c91a")
                        },
                        new
                        {
                            Id = new Guid("0194f245-5105-7247-bc43-7947827e37a3"),
                            PermissionCode = 21,
                            RoleId = new Guid("0194f245-5105-78f5-8a31-ae761f22c91a")
                        },
                        new
                        {
                            Id = new Guid("0194f245-5105-7358-a689-95268f10aa14"),
                            PermissionCode = 22,
                            RoleId = new Guid("0194f245-5105-78f5-8a31-ae761f22c91a")
                        },
                        new
                        {
                            Id = new Guid("0194f245-5105-78c4-b810-677776b43aa3"),
                            PermissionCode = 23,
                            RoleId = new Guid("0194f245-5105-78f5-8a31-ae761f22c91a")
                        },
                        new
                        {
                            Id = new Guid("0194f245-5105-74b0-a916-b95a0894913e"),
                            PermissionCode = 24,
                            RoleId = new Guid("0194f245-5105-78f5-8a31-ae761f22c91a")
                        },
                        new
                        {
                            Id = new Guid("0194f245-5105-7531-a8f2-6c45f65c71b1"),
                            PermissionCode = 25,
                            RoleId = new Guid("0194f245-5105-78f5-8a31-ae761f22c91a")
                        },
                        new
                        {
                            Id = new Guid("0194f245-5105-7f19-9768-94fed7fac0b1"),
                            PermissionCode = 26,
                            RoleId = new Guid("0194f245-5105-78f5-8a31-ae761f22c91a")
                        },
                        new
                        {
                            Id = new Guid("0194f245-5105-7707-a324-070ec3b9727d"),
                            PermissionCode = 27,
                            RoleId = new Guid("0194f245-5105-78f5-8a31-ae761f22c91a")
                        },
                        new
                        {
                            Id = new Guid("0194f245-5105-79db-a133-a007eeddefb0"),
                            PermissionCode = 28,
                            RoleId = new Guid("0194f245-5105-78f5-8a31-ae761f22c91a")
                        },
                        new
                        {
                            Id = new Guid("0194f245-5105-74b9-b659-82e565a1652e"),
                            PermissionCode = 1,
                            RoleId = new Guid("0194f245-5105-7ca0-8a8c-23762504af10")
                        },
                        new
                        {
                            Id = new Guid("0194f245-5105-7269-afa4-7c92d3ffd677"),
                            PermissionCode = 5,
                            RoleId = new Guid("0194f245-5105-7ca0-8a8c-23762504af10")
                        },
                        new
                        {
                            Id = new Guid("0194f245-5105-7f63-8cee-8c09f68ada0a"),
                            PermissionCode = 9,
                            RoleId = new Guid("0194f245-5105-7ca0-8a8c-23762504af10")
                        },
                        new
                        {
                            Id = new Guid("0194f245-5105-7389-9875-d920b328407b"),
                            PermissionCode = 13,
                            RoleId = new Guid("0194f245-5105-7ca0-8a8c-23762504af10")
                        },
                        new
                        {
                            Id = new Guid("0194f245-5105-7e78-9385-3dab3ad972a6"),
                            PermissionCode = 14,
                            RoleId = new Guid("0194f245-5105-7ca0-8a8c-23762504af10")
                        },
                        new
                        {
                            Id = new Guid("0194f245-5105-7e32-9034-725e86893387"),
                            PermissionCode = 15,
                            RoleId = new Guid("0194f245-5105-7ca0-8a8c-23762504af10")
                        },
                        new
                        {
                            Id = new Guid("0194f245-5105-721a-b481-bf810479a84d"),
                            PermissionCode = 16,
                            RoleId = new Guid("0194f245-5105-7ca0-8a8c-23762504af10")
                        },
                        new
                        {
                            Id = new Guid("0194f245-5105-7321-ab9c-0cf76826ac0f"),
                            PermissionCode = 17,
                            RoleId = new Guid("0194f245-5105-7ca0-8a8c-23762504af10")
                        },
                        new
                        {
                            Id = new Guid("0194f245-5105-73bc-aba7-c75da66ffa7a"),
                            PermissionCode = 18,
                            RoleId = new Guid("0194f245-5105-7ca0-8a8c-23762504af10")
                        },
                        new
                        {
                            Id = new Guid("0194f245-5105-7148-887e-c5aba21138f2"),
                            PermissionCode = 19,
                            RoleId = new Guid("0194f245-5105-7ca0-8a8c-23762504af10")
                        },
                        new
                        {
                            Id = new Guid("0194f245-5105-71f9-ba75-29b4d9ffaae1"),
                            PermissionCode = 20,
                            RoleId = new Guid("0194f245-5105-7ca0-8a8c-23762504af10")
                        },
                        new
                        {
                            Id = new Guid("0194f245-5105-7ab4-a312-0785d8d7455c"),
                            PermissionCode = 21,
                            RoleId = new Guid("0194f245-5105-7ca0-8a8c-23762504af10")
                        },
                        new
                        {
                            Id = new Guid("0194f245-5105-7b6d-81c0-19ab12e4579f"),
                            PermissionCode = 22,
                            RoleId = new Guid("0194f245-5105-7ca0-8a8c-23762504af10")
                        },
                        new
                        {
                            Id = new Guid("0194f245-5105-7ffc-9bd5-fbd5170f2177"),
                            PermissionCode = 24,
                            RoleId = new Guid("0194f245-5105-7ca0-8a8c-23762504af10")
                        },
                        new
                        {
                            Id = new Guid("0194f245-5105-7783-9f56-e8bb539ee38a"),
                            PermissionCode = 26,
                            RoleId = new Guid("0194f245-5105-7ca0-8a8c-23762504af10")
                        },
                        new
                        {
                            Id = new Guid("0194f245-5105-7cfd-8b09-934647c27f7b"),
                            PermissionCode = 27,
                            RoleId = new Guid("0194f245-5105-7ca0-8a8c-23762504af10")
                        },
                        new
                        {
                            Id = new Guid("0194f245-5105-77a3-b07e-9b415cbf6be2"),
                            PermissionCode = 28,
                            RoleId = new Guid("0194f245-5105-7ca0-8a8c-23762504af10")
                        },
                        new
                        {
                            Id = new Guid("0194f245-5105-768a-a308-3ebd23a385e7"),
                            PermissionCode = 1,
                            RoleId = new Guid("0194f245-5105-782d-811a-0a383b34545c")
                        },
                        new
                        {
                            Id = new Guid("0194f245-5105-75a0-8d64-4057f50f2624"),
                            PermissionCode = 5,
                            RoleId = new Guid("0194f245-5105-782d-811a-0a383b34545c")
                        },
                        new
                        {
                            Id = new Guid("0194f245-5105-7a63-878c-269351dee3b9"),
                            PermissionCode = 9,
                            RoleId = new Guid("0194f245-5105-782d-811a-0a383b34545c")
                        },
                        new
                        {
                            Id = new Guid("0194f245-5105-714f-b97d-9ab2c5bd9934"),
                            PermissionCode = 13,
                            RoleId = new Guid("0194f245-5105-782d-811a-0a383b34545c")
                        },
                        new
                        {
                            Id = new Guid("0194f245-5105-7b43-9d73-70b87dfbaaae"),
                            PermissionCode = 17,
                            RoleId = new Guid("0194f245-5105-782d-811a-0a383b34545c")
                        },
                        new
                        {
                            Id = new Guid("0194f245-5105-74dd-949b-4d5cabf6a13e"),
                            PermissionCode = 21,
                            RoleId = new Guid("0194f245-5105-782d-811a-0a383b34545c")
                        },
                        new
                        {
                            Id = new Guid("0194f245-5105-732b-8d35-3f8f95dcd1c1"),
                            PermissionCode = 25,
                            RoleId = new Guid("0194f245-5105-782d-811a-0a383b34545c")
                        });
                });

            modelBuilder.Entity("Infrastructure.Entities.Identity.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("Infrastructure.Entities.Identity.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue(new DateTime(2025, 2, 10, 23, 50, 16, 624, DateTimeKind.Utc).AddTicks(208))
                        .HasColumnName("CreatedAt");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasColumnName("Name");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue(new DateTime(2025, 2, 10, 23, 50, 16, 625, DateTimeKind.Utc).AddTicks(3685))
                        .HasColumnName("UpdatedAt");

                    b.HasKey("Id");

                    b.ToTable("Roles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("0194f245-5105-78f5-8a31-ae761f22c91a"),
                            CreatedAt = new DateTime(2025, 2, 10, 23, 50, 16, 581, DateTimeKind.Utc).AddTicks(7554),
                            Name = "Administrator",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("0194f245-5105-7ca0-8a8c-23762504af10"),
                            CreatedAt = new DateTime(2025, 2, 10, 23, 50, 16, 581, DateTimeKind.Utc).AddTicks(7855),
                            Name = "Developer",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("0194f245-5105-782d-811a-0a383b34545c"),
                            CreatedAt = new DateTime(2025, 2, 10, 23, 50, 16, 581, DateTimeKind.Utc).AddTicks(7858),
                            Name = "QA",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("Infrastructure.Entities.Identity.Team", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("Teams", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("0194f245-5106-7fef-8188-dc5471e8863a"),
                            Name = "Admins",
                            RoleId = new Guid("0194f245-5105-78f5-8a31-ae761f22c91a")
                        },
                        new
                        {
                            Id = new Guid("0194f245-5106-7205-895a-bdea97f88960"),
                            Name = "Devs",
                            RoleId = new Guid("0194f245-5105-7ca0-8a8c-23762504af10")
                        },
                        new
                        {
                            Id = new Guid("0194f245-5106-7756-b770-75b7bcfb0bef"),
                            Name = "QA",
                            RoleId = new Guid("0194f245-5105-782d-811a-0a383b34545c")
                        });
                });

            modelBuilder.Entity("Infrastructure.Entities.Identity.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("Id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue(new DateTime(2025, 2, 10, 23, 50, 16, 641, DateTimeKind.Utc).AddTicks(1243))
                        .HasColumnName("CreatedAt");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasColumnName("Email");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasColumnName("Name");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasColumnName("Password");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue(new DateTime(2025, 2, 10, 23, 50, 16, 641, DateTimeKind.Utc).AddTicks(1959))
                        .HasColumnName("UpdatedAt");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("EmailIndex");

                    b.ToTable("Users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("0194f245-5106-71d7-bd7c-ca3483dfcd75"),
                            CreatedAt = new DateTime(2025, 2, 10, 23, 50, 16, 582, DateTimeKind.Utc).AddTicks(6635),
                            Email = "admin@admin.com",
                            Name = "admin",
                            Password = "6EJq+e3UFqtQXMa+2/ZxFaYyn/nKHjyIYW/ZpGzgJz5V3o+k",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("0194f245-5116-7d06-89ee-97ae43361765"),
                            CreatedAt = new DateTime(2025, 2, 10, 23, 50, 16, 598, DateTimeKind.Utc).AddTicks(6997),
                            Email = "dev@dev.com",
                            Name = "dev",
                            Password = "bdHMw/kQ/kYRfZ1ikpvF2BHurtom3D33Wa7cJmCoKhuyJm56",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("0194f245-511c-7b83-add7-cc843e2d92bc"),
                            CreatedAt = new DateTime(2025, 2, 10, 23, 50, 16, 604, DateTimeKind.Utc).AddTicks(3295),
                            Email = "qa@qa.com",
                            Name = "qa",
                            Password = "0ZWDIz/6zoO80i+Lm7LxBMO/3QyDQ1r08+k0JnR2QuyrQ7HA",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("Infrastructure.Entities.Platform", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Address")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Address")
                        .IsUnique()
                        .HasDatabaseName("AddressIndex");

                    b.ToTable("Platforms", (string)null);
                });

            modelBuilder.Entity("Infrastructure.Entities.PlatformStat", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<double>("CpuUsage")
                        .HasColumnType("REAL");

                    b.Property<long>("Created")
                        .HasColumnType("INTEGER");

                    b.Property<double>("MemoryUsage")
                        .HasColumnType("REAL");

                    b.Property<Guid>("PlatformId")
                        .HasColumnType("TEXT");

                    b.Property<double>("RxBytes")
                        .HasColumnType("REAL");

                    b.Property<double>("TxBytes")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("Created")
                        .IsUnique();

                    b.HasIndex("PlatformId");

                    b.ToTable("PlatformStats", (string)null);
                });

            modelBuilder.Entity("Infrastructure.Entities.Registry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Configuration")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Registries", (string)null);
                });

            modelBuilder.Entity("Infrastructure.Entities.SwarmInfo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("ControlAvailable")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Error")
                        .HasColumnType("TEXT");

                    b.Property<string>("LocalNodeState")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<long>("Managers")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NodeAddr")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("NodeID")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<long>("Nodes")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("SystemInfoId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SystemInfoId")
                        .IsUnique();

                    b.ToTable("SwarmsInfo", (string)null);
                });

            modelBuilder.Entity("Infrastructure.Entities.SwarmPeer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Addr")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("NodeID")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SwarmInfoId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SwarmInfoId");

                    b.ToTable("SwarmsPeer", (string)null);
                });

            modelBuilder.Entity("Infrastructure.Entities.SystemInfo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AgentVersion")
                        .HasColumnType("TEXT");

                    b.Property<string>("Architecture")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<long>("Containers")
                        .HasColumnType("INTEGER");

                    b.Property<long>("ContainersPaused")
                        .HasColumnType("INTEGER");

                    b.Property<long>("ContainersRunning")
                        .HasColumnType("INTEGER");

                    b.Property<long>("ContainersStopped")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DaemonId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Driver")
                        .HasColumnType("TEXT");

                    b.Property<long>("Images")
                        .HasColumnType("INTEGER");

                    b.Property<long>("MemTotal")
                        .HasColumnType("INTEGER");

                    b.Property<long>("Ncpu")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NetworksCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OperatingSystem")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("OsType")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("OsVersion")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PlatformId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ServerVersion")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<int>("VolumesCount")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PlatformId")
                        .IsUnique();

                    b.ToTable("SystemsInfo", (string)null);
                });

            modelBuilder.Entity("Infrastructure.EntityFramework.JoiningTables.UserTeam", b =>
                {
                    b.Property<Guid>("TeamId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("TeamId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("UsersTeams");

                    b.HasData(
                        new
                        {
                            TeamId = new Guid("0194f245-5106-7fef-8188-dc5471e8863a"),
                            UserId = new Guid("0194f245-5106-71d7-bd7c-ca3483dfcd75")
                        },
                        new
                        {
                            TeamId = new Guid("0194f245-5106-7205-895a-bdea97f88960"),
                            UserId = new Guid("0194f245-5116-7d06-89ee-97ae43361765")
                        },
                        new
                        {
                            TeamId = new Guid("0194f245-5106-7756-b770-75b7bcfb0bef"),
                            UserId = new Guid("0194f245-511c-7b83-add7-cc843e2d92bc")
                        });
                });

            modelBuilder.Entity("Infrastructure.Entities.ContainerInfo", b =>
                {
                    b.HasOne("Infrastructure.Entities.Platform", "Platform")
                        .WithMany()
                        .HasForeignKey("PlatformId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsMany("Infrastructure.Entities.ContainerPort", "Ports", b1 =>
                        {
                            b1.Property<Guid>("ContainerInfoId")
                                .HasColumnType("TEXT");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAddOrUpdate()
                                .HasColumnType("INTEGER");

                            b1.Property<string>("IP")
                                .HasColumnType("TEXT");

                            b1.Property<int?>("PrivatePort")
                                .HasColumnType("INTEGER");

                            b1.Property<int?>("PublicPort")
                                .HasColumnType("INTEGER");

                            b1.HasKey("ContainerInfoId", "__synthesizedOrdinal");

                            b1.ToTable("ContainersInfo");

                            b1.ToJson("Ports");

                            b1.WithOwner()
                                .HasForeignKey("ContainerInfoId");
                        });

                    b.Navigation("Platform");

                    b.Navigation("Ports");
                });

            modelBuilder.Entity("Infrastructure.Entities.ContainerStat", b =>
                {
                    b.HasOne("Infrastructure.Entities.ContainerInfo", null)
                        .WithMany("Stats")
                        .HasForeignKey("ContainerInfoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Infrastructure.Entities.Identity.Permission", b =>
                {
                    b.HasOne("Infrastructure.Entities.Identity.Role", null)
                        .WithMany("Permissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Infrastructure.Entities.Identity.RefreshToken", b =>
                {
                    b.HasOne("Infrastructure.Entities.Identity.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Infrastructure.Entities.Identity.Team", b =>
                {
                    b.HasOne("Infrastructure.Entities.Identity.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Infrastructure.Entities.PlatformStat", b =>
                {
                    b.HasOne("Infrastructure.Entities.Platform", null)
                        .WithMany("Stats")
                        .HasForeignKey("PlatformId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Infrastructure.Entities.SwarmInfo", b =>
                {
                    b.HasOne("Infrastructure.Entities.SystemInfo", "SystemInfo")
                        .WithOne("SwarmInfo")
                        .HasForeignKey("Infrastructure.Entities.SwarmInfo", "SystemInfoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SystemInfo");
                });

            modelBuilder.Entity("Infrastructure.Entities.SwarmPeer", b =>
                {
                    b.HasOne("Infrastructure.Entities.SwarmInfo", "SwarmInfo")
                        .WithMany("RemoteManagers")
                        .HasForeignKey("SwarmInfoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SwarmInfo");
                });

            modelBuilder.Entity("Infrastructure.Entities.SystemInfo", b =>
                {
                    b.HasOne("Infrastructure.Entities.Platform", "Platform")
                        .WithOne("SystemInfo")
                        .HasForeignKey("Infrastructure.Entities.SystemInfo", "PlatformId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Platform");
                });

            modelBuilder.Entity("Infrastructure.EntityFramework.JoiningTables.UserTeam", b =>
                {
                    b.HasOne("Infrastructure.Entities.Identity.Team", null)
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Infrastructure.Entities.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Infrastructure.Entities.ContainerInfo", b =>
                {
                    b.Navigation("Stats");
                });

            modelBuilder.Entity("Infrastructure.Entities.Identity.Role", b =>
                {
                    b.Navigation("Permissions");
                });

            modelBuilder.Entity("Infrastructure.Entities.Identity.User", b =>
                {
                    b.Navigation("RefreshTokens");
                });

            modelBuilder.Entity("Infrastructure.Entities.Platform", b =>
                {
                    b.Navigation("Stats");

                    b.Navigation("SystemInfo");
                });

            modelBuilder.Entity("Infrastructure.Entities.SwarmInfo", b =>
                {
                    b.Navigation("RemoteManagers");
                });

            modelBuilder.Entity("Infrastructure.Entities.SystemInfo", b =>
                {
                    b.Navigation("SwarmInfo");
                });
#pragma warning restore 612, 618
        }
    }
}
