// <auto-generated />
using System;
using Infrastructure.EntityFramework;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.4");

            modelBuilder.Entity("Infrastructure.Entities.ContainerInfo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ContainerId")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<long>("Created")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Image")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PlatformId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Ports")
                        .HasColumnType("TEXT");

                    b.Property<string>("Stack")
                        .HasColumnType("TEXT");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ContainerId")
                        .IsUnique();

                    b.HasIndex("PlatformId");

                    b.ToTable("ContainersInfo", (string)null);
                });

            modelBuilder.Entity("Infrastructure.Entities.ContainerStat", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ContainerInfoId")
                        .HasColumnType("TEXT");

                    b.Property<double?>("CpuUsage")
                        .HasColumnType("REAL");

                    b.Property<long>("Created")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("MemoryLimit")
                        .HasColumnType("REAL");

                    b.Property<double?>("MemoryUsage")
                        .HasColumnType("REAL");

                    b.Property<long?>("RxBytes")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("TxBytes")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ContainerInfoId");

                    b.ToTable("ContainerStats", (string)null);
                });

            modelBuilder.Entity("Infrastructure.Entities.Identity.Permission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("PermissionCode")
                        .HasColumnType("INTEGER")
                        .HasColumnName("PermissionCode");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("Permissions", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("0196b1e0-492b-7585-b815-32e824a89b33"),
                            PermissionCode = 1,
                            RoleId = new Guid("0196b1e0-492b-7a8a-92f9-bc554a2558c5")
                        },
                        new
                        {
                            Id = new Guid("0196b1e0-492b-71ee-81d6-79e231bb8f6f"),
                            PermissionCode = 2,
                            RoleId = new Guid("0196b1e0-492b-7a8a-92f9-bc554a2558c5")
                        },
                        new
                        {
                            Id = new Guid("0196b1e0-492b-71e3-9341-fb5bdd5fc539"),
                            PermissionCode = 3,
                            RoleId = new Guid("0196b1e0-492b-7a8a-92f9-bc554a2558c5")
                        },
                        new
                        {
                            Id = new Guid("0196b1e0-492b-7415-be6f-99f83b24c145"),
                            PermissionCode = 4,
                            RoleId = new Guid("0196b1e0-492b-7a8a-92f9-bc554a2558c5")
                        },
                        new
                        {
                            Id = new Guid("0196b1e0-492b-70d2-b54c-1772d4405564"),
                            PermissionCode = 5,
                            RoleId = new Guid("0196b1e0-492b-7a8a-92f9-bc554a2558c5")
                        },
                        new
                        {
                            Id = new Guid("0196b1e0-492b-78a6-89d1-e0e18555f533"),
                            PermissionCode = 6,
                            RoleId = new Guid("0196b1e0-492b-7a8a-92f9-bc554a2558c5")
                        },
                        new
                        {
                            Id = new Guid("0196b1e0-492b-7d9d-8c84-11fc2cb82a89"),
                            PermissionCode = 7,
                            RoleId = new Guid("0196b1e0-492b-7a8a-92f9-bc554a2558c5")
                        },
                        new
                        {
                            Id = new Guid("0196b1e0-492b-7814-9760-710c2afaa026"),
                            PermissionCode = 8,
                            RoleId = new Guid("0196b1e0-492b-7a8a-92f9-bc554a2558c5")
                        },
                        new
                        {
                            Id = new Guid("0196b1e0-492b-7a98-8f09-169a65e58599"),
                            PermissionCode = 9,
                            RoleId = new Guid("0196b1e0-492b-7a8a-92f9-bc554a2558c5")
                        },
                        new
                        {
                            Id = new Guid("0196b1e0-492b-7969-807e-b296e8ccc6a4"),
                            PermissionCode = 10,
                            RoleId = new Guid("0196b1e0-492b-7a8a-92f9-bc554a2558c5")
                        },
                        new
                        {
                            Id = new Guid("0196b1e0-492b-7db5-bae1-9c0d7854e530"),
                            PermissionCode = 11,
                            RoleId = new Guid("0196b1e0-492b-7a8a-92f9-bc554a2558c5")
                        },
                        new
                        {
                            Id = new Guid("0196b1e0-492b-795f-80a9-daaaa92b0073"),
                            PermissionCode = 12,
                            RoleId = new Guid("0196b1e0-492b-7a8a-92f9-bc554a2558c5")
                        },
                        new
                        {
                            Id = new Guid("0196b1e0-492b-75a4-a02c-4fa4fca755ee"),
                            PermissionCode = 13,
                            RoleId = new Guid("0196b1e0-492b-7a8a-92f9-bc554a2558c5")
                        },
                        new
                        {
                            Id = new Guid("0196b1e0-492b-7626-8981-3935f25c1a08"),
                            PermissionCode = 14,
                            RoleId = new Guid("0196b1e0-492b-7a8a-92f9-bc554a2558c5")
                        },
                        new
                        {
                            Id = new Guid("0196b1e0-492b-7216-b4fb-037f6797681f"),
                            PermissionCode = 15,
                            RoleId = new Guid("0196b1e0-492b-7a8a-92f9-bc554a2558c5")
                        },
                        new
                        {
                            Id = new Guid("0196b1e0-492b-7f5b-ab40-577a46f08869"),
                            PermissionCode = 16,
                            RoleId = new Guid("0196b1e0-492b-7a8a-92f9-bc554a2558c5")
                        },
                        new
                        {
                            Id = new Guid("0196b1e0-492b-7471-be83-d10b94434bae"),
                            PermissionCode = 17,
                            RoleId = new Guid("0196b1e0-492b-7a8a-92f9-bc554a2558c5")
                        },
                        new
                        {
                            Id = new Guid("0196b1e0-492b-73de-a204-72647423c2a6"),
                            PermissionCode = 18,
                            RoleId = new Guid("0196b1e0-492b-7a8a-92f9-bc554a2558c5")
                        },
                        new
                        {
                            Id = new Guid("0196b1e0-492b-78ec-9b2d-2076d73c6f51"),
                            PermissionCode = 19,
                            RoleId = new Guid("0196b1e0-492b-7a8a-92f9-bc554a2558c5")
                        },
                        new
                        {
                            Id = new Guid("0196b1e0-492b-70d3-9db0-3e2de176cdbe"),
                            PermissionCode = 20,
                            RoleId = new Guid("0196b1e0-492b-7a8a-92f9-bc554a2558c5")
                        },
                        new
                        {
                            Id = new Guid("0196b1e0-492b-7b91-a176-243bda513513"),
                            PermissionCode = 21,
                            RoleId = new Guid("0196b1e0-492b-7a8a-92f9-bc554a2558c5")
                        },
                        new
                        {
                            Id = new Guid("0196b1e0-492b-7738-9197-f8b9854f317a"),
                            PermissionCode = 22,
                            RoleId = new Guid("0196b1e0-492b-7a8a-92f9-bc554a2558c5")
                        },
                        new
                        {
                            Id = new Guid("0196b1e0-492b-78be-af08-868a0659f8e7"),
                            PermissionCode = 23,
                            RoleId = new Guid("0196b1e0-492b-7a8a-92f9-bc554a2558c5")
                        },
                        new
                        {
                            Id = new Guid("0196b1e0-492b-70b1-a22e-5638d8cacd75"),
                            PermissionCode = 24,
                            RoleId = new Guid("0196b1e0-492b-7a8a-92f9-bc554a2558c5")
                        },
                        new
                        {
                            Id = new Guid("0196b1e0-492b-71d2-bdd4-b7359f539384"),
                            PermissionCode = 25,
                            RoleId = new Guid("0196b1e0-492b-7a8a-92f9-bc554a2558c5")
                        },
                        new
                        {
                            Id = new Guid("0196b1e0-492b-7ed9-b15a-a080ecd69686"),
                            PermissionCode = 26,
                            RoleId = new Guid("0196b1e0-492b-7a8a-92f9-bc554a2558c5")
                        },
                        new
                        {
                            Id = new Guid("0196b1e0-492b-754f-8e24-83e3e6e703f4"),
                            PermissionCode = 27,
                            RoleId = new Guid("0196b1e0-492b-7a8a-92f9-bc554a2558c5")
                        },
                        new
                        {
                            Id = new Guid("0196b1e0-492b-7a71-b140-c72779dcf1b0"),
                            PermissionCode = 28,
                            RoleId = new Guid("0196b1e0-492b-7a8a-92f9-bc554a2558c5")
                        },
                        new
                        {
                            Id = new Guid("0196b1e0-492b-70bf-a199-7d1864a0b525"),
                            PermissionCode = 1,
                            RoleId = new Guid("0196b1e0-492b-76de-befb-6a62e6c3cbb1")
                        },
                        new
                        {
                            Id = new Guid("0196b1e0-492b-7347-a657-1714d2889aa4"),
                            PermissionCode = 5,
                            RoleId = new Guid("0196b1e0-492b-76de-befb-6a62e6c3cbb1")
                        },
                        new
                        {
                            Id = new Guid("0196b1e0-492b-704b-8b5d-4588441a02f3"),
                            PermissionCode = 9,
                            RoleId = new Guid("0196b1e0-492b-76de-befb-6a62e6c3cbb1")
                        },
                        new
                        {
                            Id = new Guid("0196b1e0-492b-7291-8994-92f17b0769ac"),
                            PermissionCode = 13,
                            RoleId = new Guid("0196b1e0-492b-76de-befb-6a62e6c3cbb1")
                        },
                        new
                        {
                            Id = new Guid("0196b1e0-492b-7e05-a019-766067b1824b"),
                            PermissionCode = 14,
                            RoleId = new Guid("0196b1e0-492b-76de-befb-6a62e6c3cbb1")
                        },
                        new
                        {
                            Id = new Guid("0196b1e0-492b-700d-9497-9371c945a1de"),
                            PermissionCode = 15,
                            RoleId = new Guid("0196b1e0-492b-76de-befb-6a62e6c3cbb1")
                        },
                        new
                        {
                            Id = new Guid("0196b1e0-492b-730a-8f7a-9a64a32d8735"),
                            PermissionCode = 16,
                            RoleId = new Guid("0196b1e0-492b-76de-befb-6a62e6c3cbb1")
                        },
                        new
                        {
                            Id = new Guid("0196b1e0-492b-7a60-b71b-8eea68d52d24"),
                            PermissionCode = 17,
                            RoleId = new Guid("0196b1e0-492b-76de-befb-6a62e6c3cbb1")
                        },
                        new
                        {
                            Id = new Guid("0196b1e0-492b-7ff0-bced-7c61179fadb3"),
                            PermissionCode = 18,
                            RoleId = new Guid("0196b1e0-492b-76de-befb-6a62e6c3cbb1")
                        },
                        new
                        {
                            Id = new Guid("0196b1e0-492b-73c9-b1d7-2a538f10e560"),
                            PermissionCode = 19,
                            RoleId = new Guid("0196b1e0-492b-76de-befb-6a62e6c3cbb1")
                        },
                        new
                        {
                            Id = new Guid("0196b1e0-492b-77aa-b692-4c05dcf61ffa"),
                            PermissionCode = 20,
                            RoleId = new Guid("0196b1e0-492b-76de-befb-6a62e6c3cbb1")
                        },
                        new
                        {
                            Id = new Guid("0196b1e0-492b-70fb-8ca0-9d3eb60f3461"),
                            PermissionCode = 21,
                            RoleId = new Guid("0196b1e0-492b-76de-befb-6a62e6c3cbb1")
                        },
                        new
                        {
                            Id = new Guid("0196b1e0-492b-726c-a739-46f3a66d5466"),
                            PermissionCode = 22,
                            RoleId = new Guid("0196b1e0-492b-76de-befb-6a62e6c3cbb1")
                        },
                        new
                        {
                            Id = new Guid("0196b1e0-492b-75a4-b2de-ef47a39a4cc1"),
                            PermissionCode = 24,
                            RoleId = new Guid("0196b1e0-492b-76de-befb-6a62e6c3cbb1")
                        },
                        new
                        {
                            Id = new Guid("0196b1e0-492b-726e-9fc3-fd5034e731c7"),
                            PermissionCode = 26,
                            RoleId = new Guid("0196b1e0-492b-76de-befb-6a62e6c3cbb1")
                        },
                        new
                        {
                            Id = new Guid("0196b1e0-492b-7f39-b85f-ab3482c67d0f"),
                            PermissionCode = 27,
                            RoleId = new Guid("0196b1e0-492b-76de-befb-6a62e6c3cbb1")
                        },
                        new
                        {
                            Id = new Guid("0196b1e0-492b-7f15-ab8a-f67df34e6a2f"),
                            PermissionCode = 28,
                            RoleId = new Guid("0196b1e0-492b-76de-befb-6a62e6c3cbb1")
                        },
                        new
                        {
                            Id = new Guid("0196b1e0-492b-7b3f-93b5-84a008729064"),
                            PermissionCode = 1,
                            RoleId = new Guid("0196b1e0-492b-7f03-91bc-4a84099966e3")
                        },
                        new
                        {
                            Id = new Guid("0196b1e0-492b-75a2-94d4-be7421b0d246"),
                            PermissionCode = 5,
                            RoleId = new Guid("0196b1e0-492b-7f03-91bc-4a84099966e3")
                        },
                        new
                        {
                            Id = new Guid("0196b1e0-492b-703a-a18d-df37845d4a1a"),
                            PermissionCode = 9,
                            RoleId = new Guid("0196b1e0-492b-7f03-91bc-4a84099966e3")
                        },
                        new
                        {
                            Id = new Guid("0196b1e0-492b-736c-a524-d5f0721a14e6"),
                            PermissionCode = 13,
                            RoleId = new Guid("0196b1e0-492b-7f03-91bc-4a84099966e3")
                        },
                        new
                        {
                            Id = new Guid("0196b1e0-492b-7b60-9904-b8e036fa195f"),
                            PermissionCode = 17,
                            RoleId = new Guid("0196b1e0-492b-7f03-91bc-4a84099966e3")
                        },
                        new
                        {
                            Id = new Guid("0196b1e0-492b-7711-a0d6-920a4124327b"),
                            PermissionCode = 21,
                            RoleId = new Guid("0196b1e0-492b-7f03-91bc-4a84099966e3")
                        },
                        new
                        {
                            Id = new Guid("0196b1e0-492b-79ba-acf6-f95fa8e855f6"),
                            PermissionCode = 25,
                            RoleId = new Guid("0196b1e0-492b-7f03-91bc-4a84099966e3")
                        });
                });

            modelBuilder.Entity("Infrastructure.Entities.Identity.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("Infrastructure.Entities.Identity.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue(new DateTime(2025, 5, 8, 21, 49, 48, 237, DateTimeKind.Utc).AddTicks(9522))
                        .HasColumnName("CreatedAt");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasColumnName("Name");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue(new DateTime(2025, 5, 8, 21, 49, 48, 239, DateTimeKind.Utc).AddTicks(4092))
                        .HasColumnName("UpdatedAt");

                    b.HasKey("Id");

                    b.ToTable("Roles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("0196b1e0-492b-7a8a-92f9-bc554a2558c5"),
                            CreatedAt = new DateTime(2025, 5, 8, 21, 49, 48, 203, DateTimeKind.Utc).AddTicks(1097),
                            Name = "Administrator",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("0196b1e0-492b-76de-befb-6a62e6c3cbb1"),
                            CreatedAt = new DateTime(2025, 5, 8, 21, 49, 48, 203, DateTimeKind.Utc).AddTicks(1365),
                            Name = "Developer",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("0196b1e0-492b-7f03-91bc-4a84099966e3"),
                            CreatedAt = new DateTime(2025, 5, 8, 21, 49, 48, 203, DateTimeKind.Utc).AddTicks(1368),
                            Name = "QA",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("Infrastructure.Entities.Identity.Team", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("Teams", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("0196b1e0-492b-79ff-984d-62a33392544c"),
                            Name = "Admins",
                            RoleId = new Guid("0196b1e0-492b-7a8a-92f9-bc554a2558c5")
                        },
                        new
                        {
                            Id = new Guid("0196b1e0-492b-71ee-9a1a-022d58d8c8cc"),
                            Name = "Devs",
                            RoleId = new Guid("0196b1e0-492b-76de-befb-6a62e6c3cbb1")
                        },
                        new
                        {
                            Id = new Guid("0196b1e0-492b-7e5d-9395-10e838cb3622"),
                            Name = "QA",
                            RoleId = new Guid("0196b1e0-492b-7f03-91bc-4a84099966e3")
                        });
                });

            modelBuilder.Entity("Infrastructure.Entities.Identity.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("Id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue(new DateTime(2025, 5, 8, 21, 49, 48, 247, DateTimeKind.Utc).AddTicks(2411))
                        .HasColumnName("CreatedAt");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasColumnName("Email");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasColumnName("Name");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasColumnName("Password");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue(new DateTime(2025, 5, 8, 21, 49, 48, 247, DateTimeKind.Utc).AddTicks(3352))
                        .HasColumnName("UpdatedAt");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("EmailIndex");

                    b.ToTable("Users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("0196b1e0-492b-7ca4-8cde-26605ba867c0"),
                            CreatedAt = new DateTime(2025, 5, 8, 21, 49, 48, 203, DateTimeKind.Utc).AddTicks(8175),
                            Email = "admin@admin.com",
                            Name = "admin",
                            Password = "UC6Q2farx8LScvyfNsHA99c8ZA7vItC4rfFHQYuN4Or00cry",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("0196b1e0-4936-79ea-941f-7666e1922dad"),
                            CreatedAt = new DateTime(2025, 5, 8, 21, 49, 48, 214, DateTimeKind.Utc).AddTicks(8986),
                            Email = "dev@dev.com",
                            Name = "dev",
                            Password = "CUro6w0VVGmrSwf1IXcneYi/1liBoSZxp4et9I5xkowrSuEM",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("0196b1e0-493c-75c0-a56c-058af194621b"),
                            CreatedAt = new DateTime(2025, 5, 8, 21, 49, 48, 220, DateTimeKind.Utc).AddTicks(1297),
                            Email = "qa@qa.com",
                            Name = "qa",
                            Password = "dnby9q+gleI5kInorTiRNmBj3nx8Rv7+p84g/Oxu010CRnTT",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("Infrastructure.Entities.Identity.UserTeam", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "TeamId");

                    b.HasIndex("TeamId");

                    b.ToTable("UsersTeams");

                    b.HasData(
                        new
                        {
                            UserId = new Guid("0196b1e0-492b-7ca4-8cde-26605ba867c0"),
                            TeamId = new Guid("0196b1e0-492b-79ff-984d-62a33392544c")
                        },
                        new
                        {
                            UserId = new Guid("0196b1e0-4936-79ea-941f-7666e1922dad"),
                            TeamId = new Guid("0196b1e0-492b-71ee-9a1a-022d58d8c8cc")
                        },
                        new
                        {
                            UserId = new Guid("0196b1e0-493c-75c0-a56c-058af194621b"),
                            TeamId = new Guid("0196b1e0-492b-7e5d-9395-10e838cb3622")
                        });
                });

            modelBuilder.Entity("Infrastructure.Entities.Platform", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Address")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("AgentVersion")
                        .HasColumnType("TEXT");

                    b.Property<string>("Architecture")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<long>("Containers")
                        .HasColumnType("INTEGER");

                    b.Property<long>("ContainersPaused")
                        .HasColumnType("INTEGER");

                    b.Property<long>("ContainersRunning")
                        .HasColumnType("INTEGER");

                    b.Property<long>("ContainersStopped")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DaemonId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Driver")
                        .HasColumnType("TEXT");

                    b.Property<long>("Images")
                        .HasColumnType("INTEGER");

                    b.Property<long>("MemTotal")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<long>("Ncpu")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NetworksCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OperatingSystem")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("OsType")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("OsVersion")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("ServerVersion")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("VolumesCount")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Address")
                        .IsUnique()
                        .HasDatabaseName("AddressIndex");

                    b.ToTable("Platforms", (string)null);
                });

            modelBuilder.Entity("Infrastructure.Entities.PlatformStat", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<double>("CpuUsage")
                        .HasColumnType("REAL");

                    b.Property<long>("Created")
                        .HasColumnType("INTEGER");

                    b.Property<double>("MemoryUsage")
                        .HasColumnType("REAL");

                    b.Property<Guid>("PlatformId")
                        .HasColumnType("TEXT");

                    b.Property<double>("RxBytes")
                        .HasColumnType("REAL");

                    b.Property<double>("TxBytes")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("Created")
                        .IsUnique();

                    b.HasIndex("PlatformId");

                    b.ToTable("PlatformStats", (string)null);
                });

            modelBuilder.Entity("Infrastructure.Entities.Registry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Configuration")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Registries", (string)null);
                });

            modelBuilder.Entity("Infrastructure.Entities.SwarmInfo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("ControlAvailable")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Error")
                        .HasColumnType("TEXT");

                    b.Property<string>("LocalNodeState")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<long>("Managers")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NodeAddr")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("NodeID")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<long>("Nodes")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("PlatformId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PlatformId")
                        .IsUnique();

                    b.ToTable("SwarmsInfo", (string)null);
                });

            modelBuilder.Entity("Infrastructure.Entities.SwarmPeer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Addr")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("NodeID")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SwarmInfoId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SwarmInfoId");

                    b.ToTable("SwarmsPeer", (string)null);
                });

            modelBuilder.Entity("Infrastructure.Entities.ContainerInfo", b =>
                {
                    b.HasOne("Infrastructure.Entities.Platform", "Platform")
                        .WithMany("ContainersInfo")
                        .HasForeignKey("PlatformId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Platform");
                });

            modelBuilder.Entity("Infrastructure.Entities.ContainerStat", b =>
                {
                    b.HasOne("Infrastructure.Entities.ContainerInfo", null)
                        .WithMany("Stats")
                        .HasForeignKey("ContainerInfoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Infrastructure.Entities.Identity.Permission", b =>
                {
                    b.HasOne("Infrastructure.Entities.Identity.Role", null)
                        .WithMany("Permissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Infrastructure.Entities.Identity.RefreshToken", b =>
                {
                    b.HasOne("Infrastructure.Entities.Identity.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Infrastructure.Entities.Identity.Team", b =>
                {
                    b.HasOne("Infrastructure.Entities.Identity.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Infrastructure.Entities.Identity.UserTeam", b =>
                {
                    b.HasOne("Infrastructure.Entities.Identity.Team", "Team")
                        .WithMany("UserTeams")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Infrastructure.Entities.Identity.User", "User")
                        .WithMany("UserTeams")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Team");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Infrastructure.Entities.PlatformStat", b =>
                {
                    b.HasOne("Infrastructure.Entities.Platform", null)
                        .WithMany("Stats")
                        .HasForeignKey("PlatformId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Infrastructure.Entities.SwarmInfo", b =>
                {
                    b.HasOne("Infrastructure.Entities.Platform", "Platform")
                        .WithOne("SwarmInfo")
                        .HasForeignKey("Infrastructure.Entities.SwarmInfo", "PlatformId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Platform");
                });

            modelBuilder.Entity("Infrastructure.Entities.SwarmPeer", b =>
                {
                    b.HasOne("Infrastructure.Entities.SwarmInfo", "SwarmInfo")
                        .WithMany("RemoteManagers")
                        .HasForeignKey("SwarmInfoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SwarmInfo");
                });

            modelBuilder.Entity("Infrastructure.Entities.ContainerInfo", b =>
                {
                    b.Navigation("Stats");
                });

            modelBuilder.Entity("Infrastructure.Entities.Identity.Role", b =>
                {
                    b.Navigation("Permissions");
                });

            modelBuilder.Entity("Infrastructure.Entities.Identity.Team", b =>
                {
                    b.Navigation("UserTeams");
                });

            modelBuilder.Entity("Infrastructure.Entities.Identity.User", b =>
                {
                    b.Navigation("RefreshTokens");

                    b.Navigation("UserTeams");
                });

            modelBuilder.Entity("Infrastructure.Entities.Platform", b =>
                {
                    b.Navigation("ContainersInfo");

                    b.Navigation("Stats");

                    b.Navigation("SwarmInfo");
                });

            modelBuilder.Entity("Infrastructure.Entities.SwarmInfo", b =>
                {
                    b.Navigation("RemoteManagers");
                });
#pragma warning restore 612, 618
        }
    }
}
