// <auto-generated />
using System;
using Infrastructure.EntityFramework;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.4");

            modelBuilder.Entity("Infrastructure.Entities.ContainerInfo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ContainerId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<long>("Created")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PlatformId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Ports")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Stack")
                        .HasColumnType("TEXT");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ContainerId")
                        .IsUnique();

                    b.HasIndex("PlatformId");

                    b.ToTable("ContainersInfo", (string)null);
                });

            modelBuilder.Entity("Infrastructure.Entities.ContainerStat", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ContainerInfoId")
                        .HasColumnType("TEXT");

                    b.Property<double?>("CpuUsage")
                        .HasColumnType("REAL");

                    b.Property<long>("Created")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("MemoryLimit")
                        .HasColumnType("REAL");

                    b.Property<double?>("MemoryUsage")
                        .HasColumnType("REAL");

                    b.Property<long?>("RxBytes")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("TxBytes")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ContainerInfoId");

                    b.ToTable("ContainerStats", (string)null);
                });

            modelBuilder.Entity("Infrastructure.Entities.Identity.Permission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("PermissionCode")
                        .HasColumnType("INTEGER")
                        .HasColumnName("PermissionCode");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("Permissions", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("0196debe-3a01-4b2d-8e1f-1a2b3c4d5e6f"),
                            PermissionCode = 13,
                            RoleId = new Guid("0196debe-0c94-7467-9b2d-397e0200276f")
                        },
                        new
                        {
                            Id = new Guid("0196debe-3a02-4b2d-8e1f-1a2b3c4d5e6f"),
                            PermissionCode = 14,
                            RoleId = new Guid("0196debe-0c94-7467-9b2d-397e0200276f")
                        },
                        new
                        {
                            Id = new Guid("0196debe-3a03-4b2d-8e1f-1a2b3c4d5e6f"),
                            PermissionCode = 15,
                            RoleId = new Guid("0196debe-0c94-7467-9b2d-397e0200276f")
                        },
                        new
                        {
                            Id = new Guid("0196debe-3a04-4b2d-8e1f-1a2b3c4d5e6f"),
                            PermissionCode = 16,
                            RoleId = new Guid("0196debe-0c94-7467-9b2d-397e0200276f")
                        },
                        new
                        {
                            Id = new Guid("0196debe-3a05-4b2d-8e1f-1a2b3c4d5e6f"),
                            PermissionCode = 17,
                            RoleId = new Guid("0196debe-0c94-7467-9b2d-397e0200276f")
                        },
                        new
                        {
                            Id = new Guid("0196debe-3a06-4b2d-8e1f-1a2b3c4d5e6f"),
                            PermissionCode = 18,
                            RoleId = new Guid("0196debe-0c94-7467-9b2d-397e0200276f")
                        },
                        new
                        {
                            Id = new Guid("0196debe-3a07-4b2d-8e1f-1a2b3c4d5e6f"),
                            PermissionCode = 19,
                            RoleId = new Guid("0196debe-0c94-7467-9b2d-397e0200276f")
                        },
                        new
                        {
                            Id = new Guid("0196debe-3a08-4b2d-8e1f-1a2b3c4d5e6f"),
                            PermissionCode = 20,
                            RoleId = new Guid("0196debe-0c94-7467-9b2d-397e0200276f")
                        },
                        new
                        {
                            Id = new Guid("0196debe-3a09-4b2d-8e1f-1a2b3c4d5e6f"),
                            PermissionCode = 21,
                            RoleId = new Guid("0196debe-0c94-7467-9b2d-397e0200276f")
                        },
                        new
                        {
                            Id = new Guid("0196debe-3a0a-4b2d-8e1f-1a2b3c4d5e6f"),
                            PermissionCode = 22,
                            RoleId = new Guid("0196debe-0c94-7467-9b2d-397e0200276f")
                        },
                        new
                        {
                            Id = new Guid("0196debe-3a0b-4b2d-8e1f-1a2b3c4d5e6f"),
                            PermissionCode = 24,
                            RoleId = new Guid("0196debe-0c94-7467-9b2d-397e0200276f")
                        },
                        new
                        {
                            Id = new Guid("0196debe-3a0c-4b2d-8e1f-1a2b3c4d5e6f"),
                            PermissionCode = 25,
                            RoleId = new Guid("0196debe-0c94-7467-9b2d-397e0200276f")
                        },
                        new
                        {
                            Id = new Guid("0196debe-3a0d-4b2d-8e1f-1a2b3c4d5e6f"),
                            PermissionCode = 26,
                            RoleId = new Guid("0196debe-0c94-7467-9b2d-397e0200276f")
                        },
                        new
                        {
                            Id = new Guid("0196debe-3a0e-4b2d-8e1f-1a2b3c4d5e6f"),
                            PermissionCode = 27,
                            RoleId = new Guid("0196debe-0c94-7467-9b2d-397e0200276f")
                        },
                        new
                        {
                            Id = new Guid("0196debe-3a0f-4b2d-8e1f-1a2b3c4d5e6f"),
                            PermissionCode = 28,
                            RoleId = new Guid("0196debe-0c94-7467-9b2d-397e0200276f")
                        },
                        new
                        {
                            Id = new Guid("0196debe-3a10-4b2d-8e1f-1a2b3c4d5e6f"),
                            PermissionCode = 30,
                            RoleId = new Guid("0196debe-0c94-7467-9b2d-397e0200276f")
                        },
                        new
                        {
                            Id = new Guid("0196debe-3a11-4b2d-8e1f-1a2b3c4d5e6f"),
                            PermissionCode = 29,
                            RoleId = new Guid("0196debe-0c94-7467-9b2d-397e0200276f")
                        },
                        new
                        {
                            Id = new Guid("0196debe-3a12-4b2d-8e1f-1a2b3c4d5e6f"),
                            PermissionCode = 1,
                            RoleId = new Guid("0196debe-2d80-76dd-b351-ade38fa29169")
                        },
                        new
                        {
                            Id = new Guid("0196debe-3a13-4b2d-8e1f-1a2b3c4d5e6f"),
                            PermissionCode = 5,
                            RoleId = new Guid("0196debe-2d80-76dd-b351-ade38fa29169")
                        },
                        new
                        {
                            Id = new Guid("0196debe-3a14-4b2d-8e1f-1a2b3c4d5e6f"),
                            PermissionCode = 9,
                            RoleId = new Guid("0196debe-2d80-76dd-b351-ade38fa29169")
                        },
                        new
                        {
                            Id = new Guid("0196debe-3a15-4b2d-8e1f-1a2b3c4d5e6f"),
                            PermissionCode = 13,
                            RoleId = new Guid("0196debe-2d80-76dd-b351-ade38fa29169")
                        },
                        new
                        {
                            Id = new Guid("0196debe-3a16-4b2d-8e1f-1a2b3c4d5e6f"),
                            PermissionCode = 17,
                            RoleId = new Guid("0196debe-2d80-76dd-b351-ade38fa29169")
                        },
                        new
                        {
                            Id = new Guid("0196debe-3a17-4b2d-8e1f-1a2b3c4d5e6f"),
                            PermissionCode = 21,
                            RoleId = new Guid("0196debe-2d80-76dd-b351-ade38fa29169")
                        },
                        new
                        {
                            Id = new Guid("0196debe-3a18-4b2d-8e1f-1a2b3c4d5e6f"),
                            PermissionCode = 25,
                            RoleId = new Guid("0196debe-2d80-76dd-b351-ade38fa29169")
                        },
                        new
                        {
                            Id = new Guid("0196debe-3a19-4b2d-8e1f-1a2b3c4d5e6f"),
                            PermissionCode = 28,
                            RoleId = new Guid("0196debe-2d80-76dd-b351-ade38fa29169")
                        });
                });

            modelBuilder.Entity("Infrastructure.Entities.Identity.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("Infrastructure.Entities.Identity.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue(new DateTime(2000, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc))
                        .HasColumnName("CreatedAt");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasColumnName("Name");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue(new DateTime(2000, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc))
                        .HasColumnName("UpdatedAt");

                    b.HasKey("Id");

                    b.ToTable("Roles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("0196debd-033b-7512-a11b-98533d063a04"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Admin",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("0196debe-0c94-7467-9b2d-397e0200276f"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Dev",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("0196debe-2d80-76dd-b351-ade38fa29169"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "QA",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("Infrastructure.Entities.Identity.Team", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("Teams", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("0196dece-e967-7d50-832c-0ca0155465a1"),
                            Name = "Admins",
                            RoleId = new Guid("0196debd-033b-7512-a11b-98533d063a04")
                        },
                        new
                        {
                            Id = new Guid("0196dece-e967-7965-afb9-f33ff2b3f0dc"),
                            Name = "Devs",
                            RoleId = new Guid("0196debe-0c94-7467-9b2d-397e0200276f")
                        },
                        new
                        {
                            Id = new Guid("0196dece-e967-755f-9c6a-5ba5a34577f1"),
                            Name = "QA",
                            RoleId = new Guid("0196debe-2d80-76dd-b351-ade38fa29169")
                        });
                });

            modelBuilder.Entity("Infrastructure.Entities.Identity.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("Id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue(new DateTime(2000, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc))
                        .HasColumnName("CreatedAt");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasColumnName("Email");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasColumnName("Name");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasColumnName("Password");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue(new DateTime(2000, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc))
                        .HasColumnName("UpdatedAt");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("EmailIndex");

                    b.ToTable("Users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("0196ded1-13f1-77ce-884e-3cb636ec09a8"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "admin@admin.com",
                            Name = "admin",
                            Password = "/VtxS3rzyzEIhP0i6Ehq72mGCarCK+xxCMcMXo4N5WMavIl/",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("0196ded1-13f1-73fb-acf0-188115c01c0e"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "dev@dev.com",
                            Name = "dev",
                            Password = "bstIzQ7Axj+ZtX0eo89tp/8G1+oTO4BTrI+54+Ou7MKVKBwX",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("0196ded1-13f1-743a-8a1b-5e243048c77e"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "qa@qa.com",
                            Name = "qa",
                            Password = "DZrfPl29P870AAeeCz/rDj2K/68NYT2gECxx5KSnEBZdjZ1i",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("Infrastructure.Entities.Identity.UserTeam", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "TeamId");

                    b.HasIndex("TeamId");

                    b.ToTable("UsersTeams");

                    b.HasData(
                        new
                        {
                            UserId = new Guid("0196ded1-13f1-77ce-884e-3cb636ec09a8"),
                            TeamId = new Guid("0196dece-e967-7d50-832c-0ca0155465a1")
                        },
                        new
                        {
                            UserId = new Guid("0196ded1-13f1-73fb-acf0-188115c01c0e"),
                            TeamId = new Guid("0196dece-e967-7965-afb9-f33ff2b3f0dc")
                        },
                        new
                        {
                            UserId = new Guid("0196ded1-13f1-743a-8a1b-5e243048c77e"),
                            TeamId = new Guid("0196dece-e967-755f-9c6a-5ba5a34577f1")
                        });
                });

            modelBuilder.Entity("Infrastructure.Entities.Platform", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("AgentVersion")
                        .HasColumnType("TEXT");

                    b.Property<string>("Architecture")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<long>("Containers")
                        .HasColumnType("INTEGER");

                    b.Property<long>("ContainersPaused")
                        .HasColumnType("INTEGER");

                    b.Property<long>("ContainersRunning")
                        .HasColumnType("INTEGER");

                    b.Property<long>("ContainersStopped")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DaemonId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Driver")
                        .HasColumnType("TEXT");

                    b.Property<long>("Images")
                        .HasColumnType("INTEGER");

                    b.Property<long>("MemTotal")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<long>("Ncpu")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NetworksCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OperatingSystem")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("OsType")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("OsVersion")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("ServerVersion")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("VolumesCount")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Address")
                        .IsUnique()
                        .HasDatabaseName("AddressIndex");

                    b.ToTable("Platforms", (string)null);
                });

            modelBuilder.Entity("Infrastructure.Entities.PlatformStat", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<double>("CpuUsage")
                        .HasColumnType("REAL");

                    b.Property<long>("Created")
                        .HasColumnType("INTEGER");

                    b.Property<double>("MemoryUsage")
                        .HasColumnType("REAL");

                    b.Property<Guid>("PlatformId")
                        .HasColumnType("TEXT");

                    b.Property<double>("RxBytes")
                        .HasColumnType("REAL");

                    b.Property<double>("TxBytes")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("Created")
                        .IsUnique();

                    b.HasIndex("PlatformId");

                    b.ToTable("PlatformStats", (string)null);
                });

            modelBuilder.Entity("Infrastructure.Entities.Registry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Configuration")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Registries", (string)null);
                });

            modelBuilder.Entity("Infrastructure.Entities.SwarmInfo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("ControlAvailable")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Error")
                        .HasColumnType("TEXT");

                    b.Property<string>("LocalNodeState")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<long>("Managers")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NodeAddr")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("NodeID")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<long>("Nodes")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("PlatformId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PlatformId")
                        .IsUnique();

                    b.ToTable("SwarmsInfo", (string)null);
                });

            modelBuilder.Entity("Infrastructure.Entities.SwarmPeer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Addr")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("NodeID")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SwarmInfoId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SwarmInfoId");

                    b.ToTable("SwarmsPeer", (string)null);
                });

            modelBuilder.Entity("Infrastructure.Entities.ContainerInfo", b =>
                {
                    b.HasOne("Infrastructure.Entities.Platform", "Platform")
                        .WithMany("ContainersInfo")
                        .HasForeignKey("PlatformId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Platform");
                });

            modelBuilder.Entity("Infrastructure.Entities.ContainerStat", b =>
                {
                    b.HasOne("Infrastructure.Entities.ContainerInfo", null)
                        .WithMany("Stats")
                        .HasForeignKey("ContainerInfoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Infrastructure.Entities.Identity.Permission", b =>
                {
                    b.HasOne("Infrastructure.Entities.Identity.Role", null)
                        .WithMany("Permissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Infrastructure.Entities.Identity.RefreshToken", b =>
                {
                    b.HasOne("Infrastructure.Entities.Identity.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Infrastructure.Entities.Identity.Team", b =>
                {
                    b.HasOne("Infrastructure.Entities.Identity.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Infrastructure.Entities.Identity.UserTeam", b =>
                {
                    b.HasOne("Infrastructure.Entities.Identity.Team", null)
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Infrastructure.Entities.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Infrastructure.Entities.PlatformStat", b =>
                {
                    b.HasOne("Infrastructure.Entities.Platform", null)
                        .WithMany("Stats")
                        .HasForeignKey("PlatformId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Infrastructure.Entities.SwarmInfo", b =>
                {
                    b.HasOne("Infrastructure.Entities.Platform", "Platform")
                        .WithOne("SwarmInfo")
                        .HasForeignKey("Infrastructure.Entities.SwarmInfo", "PlatformId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Platform");
                });

            modelBuilder.Entity("Infrastructure.Entities.SwarmPeer", b =>
                {
                    b.HasOne("Infrastructure.Entities.SwarmInfo", "SwarmInfo")
                        .WithMany("RemoteManagers")
                        .HasForeignKey("SwarmInfoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SwarmInfo");
                });

            modelBuilder.Entity("Infrastructure.Entities.ContainerInfo", b =>
                {
                    b.Navigation("Stats");
                });

            modelBuilder.Entity("Infrastructure.Entities.Identity.Role", b =>
                {
                    b.Navigation("Permissions");
                });

            modelBuilder.Entity("Infrastructure.Entities.Identity.User", b =>
                {
                    b.Navigation("RefreshTokens");
                });

            modelBuilder.Entity("Infrastructure.Entities.Platform", b =>
                {
                    b.Navigation("ContainersInfo");

                    b.Navigation("Stats");

                    b.Navigation("SwarmInfo")
                        .IsRequired();
                });

            modelBuilder.Entity("Infrastructure.Entities.SwarmInfo", b =>
                {
                    b.Navigation("RemoteManagers");
                });
#pragma warning restore 612, 618
        }
    }
}
