// <auto-generated />
using System;
using Infrastructure.EntityFramework;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.4");

            modelBuilder.Entity("Infrastructure.Entities.ContainerInfo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ContainerId")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<long>("Created")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Image")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PlatformId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Stack")
                        .HasColumnType("TEXT");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ContainerId")
                        .IsUnique();

                    b.HasIndex("PlatformId");

                    b.ToTable("ContainersInfo", (string)null);
                });

            modelBuilder.Entity("Infrastructure.Entities.ContainerStat", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ContainerInfoId")
                        .HasColumnType("TEXT");

                    b.Property<double?>("CpuUsage")
                        .HasColumnType("REAL");

                    b.Property<long>("Created")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("MemoryLimit")
                        .HasColumnType("REAL");

                    b.Property<double?>("MemoryUsage")
                        .HasColumnType("REAL");

                    b.Property<long?>("RxBytes")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("TxBytes")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ContainerInfoId");

                    b.ToTable("ContainerStats", (string)null);
                });

            modelBuilder.Entity("Infrastructure.Entities.Identity.Permission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("PermissionCode")
                        .HasColumnType("INTEGER")
                        .HasColumnName("PermissionCode");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("Permissions", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("01968397-20e1-70c5-892b-ef4f871506bd"),
                            PermissionCode = 1,
                            RoleId = new Guid("01968397-20e1-78f5-ba61-f6d18b58e966")
                        },
                        new
                        {
                            Id = new Guid("01968397-20e1-782b-a657-33d489003914"),
                            PermissionCode = 2,
                            RoleId = new Guid("01968397-20e1-78f5-ba61-f6d18b58e966")
                        },
                        new
                        {
                            Id = new Guid("01968397-20e1-7d43-951e-24a7f5d5fb65"),
                            PermissionCode = 3,
                            RoleId = new Guid("01968397-20e1-78f5-ba61-f6d18b58e966")
                        },
                        new
                        {
                            Id = new Guid("01968397-20e1-7b81-86ea-5cbe6b42f7b8"),
                            PermissionCode = 4,
                            RoleId = new Guid("01968397-20e1-78f5-ba61-f6d18b58e966")
                        },
                        new
                        {
                            Id = new Guid("01968397-20e1-78ef-aa95-963dd4cd7409"),
                            PermissionCode = 5,
                            RoleId = new Guid("01968397-20e1-78f5-ba61-f6d18b58e966")
                        },
                        new
                        {
                            Id = new Guid("01968397-20e1-720e-8af7-fdbfc39c5c62"),
                            PermissionCode = 6,
                            RoleId = new Guid("01968397-20e1-78f5-ba61-f6d18b58e966")
                        },
                        new
                        {
                            Id = new Guid("01968397-20e1-7e8c-8ba8-c87f58218a7b"),
                            PermissionCode = 7,
                            RoleId = new Guid("01968397-20e1-78f5-ba61-f6d18b58e966")
                        },
                        new
                        {
                            Id = new Guid("01968397-20e1-738d-a232-335814efec6d"),
                            PermissionCode = 8,
                            RoleId = new Guid("01968397-20e1-78f5-ba61-f6d18b58e966")
                        },
                        new
                        {
                            Id = new Guid("01968397-20e1-754f-84a8-bcc1e310ea9e"),
                            PermissionCode = 9,
                            RoleId = new Guid("01968397-20e1-78f5-ba61-f6d18b58e966")
                        },
                        new
                        {
                            Id = new Guid("01968397-20e1-7db9-9d60-8c574eab49b9"),
                            PermissionCode = 10,
                            RoleId = new Guid("01968397-20e1-78f5-ba61-f6d18b58e966")
                        },
                        new
                        {
                            Id = new Guid("01968397-20e1-7761-987c-b26ee9f21dd9"),
                            PermissionCode = 11,
                            RoleId = new Guid("01968397-20e1-78f5-ba61-f6d18b58e966")
                        },
                        new
                        {
                            Id = new Guid("01968397-20e1-709b-bd47-0b8166ecf686"),
                            PermissionCode = 12,
                            RoleId = new Guid("01968397-20e1-78f5-ba61-f6d18b58e966")
                        },
                        new
                        {
                            Id = new Guid("01968397-20e1-7797-9522-09da5270fef8"),
                            PermissionCode = 13,
                            RoleId = new Guid("01968397-20e1-78f5-ba61-f6d18b58e966")
                        },
                        new
                        {
                            Id = new Guid("01968397-20e1-7326-b0ef-4611b5727c7f"),
                            PermissionCode = 14,
                            RoleId = new Guid("01968397-20e1-78f5-ba61-f6d18b58e966")
                        },
                        new
                        {
                            Id = new Guid("01968397-20e1-7951-8ad3-b89889f890e0"),
                            PermissionCode = 15,
                            RoleId = new Guid("01968397-20e1-78f5-ba61-f6d18b58e966")
                        },
                        new
                        {
                            Id = new Guid("01968397-20e1-7fa4-8679-c49c558fe2ee"),
                            PermissionCode = 16,
                            RoleId = new Guid("01968397-20e1-78f5-ba61-f6d18b58e966")
                        },
                        new
                        {
                            Id = new Guid("01968397-20e1-7329-8fa6-0b102d7a2507"),
                            PermissionCode = 17,
                            RoleId = new Guid("01968397-20e1-78f5-ba61-f6d18b58e966")
                        },
                        new
                        {
                            Id = new Guid("01968397-20e1-7eeb-95ce-352efdc93abd"),
                            PermissionCode = 18,
                            RoleId = new Guid("01968397-20e1-78f5-ba61-f6d18b58e966")
                        },
                        new
                        {
                            Id = new Guid("01968397-20e1-7055-9b45-c053caf66230"),
                            PermissionCode = 19,
                            RoleId = new Guid("01968397-20e1-78f5-ba61-f6d18b58e966")
                        },
                        new
                        {
                            Id = new Guid("01968397-20e1-7dc3-8751-baefcae9d7fe"),
                            PermissionCode = 20,
                            RoleId = new Guid("01968397-20e1-78f5-ba61-f6d18b58e966")
                        },
                        new
                        {
                            Id = new Guid("01968397-20e1-7624-9991-3bb45e2960dd"),
                            PermissionCode = 21,
                            RoleId = new Guid("01968397-20e1-78f5-ba61-f6d18b58e966")
                        },
                        new
                        {
                            Id = new Guid("01968397-20e1-71e3-b1f8-a529651df6e1"),
                            PermissionCode = 22,
                            RoleId = new Guid("01968397-20e1-78f5-ba61-f6d18b58e966")
                        },
                        new
                        {
                            Id = new Guid("01968397-20e1-7da8-89d8-22936106577f"),
                            PermissionCode = 23,
                            RoleId = new Guid("01968397-20e1-78f5-ba61-f6d18b58e966")
                        },
                        new
                        {
                            Id = new Guid("01968397-20e1-7cbb-933e-a79690e3cb0d"),
                            PermissionCode = 24,
                            RoleId = new Guid("01968397-20e1-78f5-ba61-f6d18b58e966")
                        },
                        new
                        {
                            Id = new Guid("01968397-20e1-7f63-95a2-71a7fbdbcda6"),
                            PermissionCode = 25,
                            RoleId = new Guid("01968397-20e1-78f5-ba61-f6d18b58e966")
                        },
                        new
                        {
                            Id = new Guid("01968397-20e1-7bc2-ae0f-7d582c3d670d"),
                            PermissionCode = 26,
                            RoleId = new Guid("01968397-20e1-78f5-ba61-f6d18b58e966")
                        },
                        new
                        {
                            Id = new Guid("01968397-20e1-779b-a217-a6b7b9589844"),
                            PermissionCode = 27,
                            RoleId = new Guid("01968397-20e1-78f5-ba61-f6d18b58e966")
                        },
                        new
                        {
                            Id = new Guid("01968397-20e1-74fa-aa81-31a5e5e3d327"),
                            PermissionCode = 28,
                            RoleId = new Guid("01968397-20e1-78f5-ba61-f6d18b58e966")
                        },
                        new
                        {
                            Id = new Guid("01968397-20e1-7359-a096-f9e26bd136b6"),
                            PermissionCode = 1,
                            RoleId = new Guid("01968397-20e1-768b-ba1e-75aca20fd1e0")
                        },
                        new
                        {
                            Id = new Guid("01968397-20e1-70c5-be1b-6c87796d12b5"),
                            PermissionCode = 5,
                            RoleId = new Guid("01968397-20e1-768b-ba1e-75aca20fd1e0")
                        },
                        new
                        {
                            Id = new Guid("01968397-20e1-77db-9e82-4efce9d44505"),
                            PermissionCode = 9,
                            RoleId = new Guid("01968397-20e1-768b-ba1e-75aca20fd1e0")
                        },
                        new
                        {
                            Id = new Guid("01968397-20e1-71dc-aa7f-b46897fa667b"),
                            PermissionCode = 13,
                            RoleId = new Guid("01968397-20e1-768b-ba1e-75aca20fd1e0")
                        },
                        new
                        {
                            Id = new Guid("01968397-20e1-71e3-9cf0-f225dcffb977"),
                            PermissionCode = 14,
                            RoleId = new Guid("01968397-20e1-768b-ba1e-75aca20fd1e0")
                        },
                        new
                        {
                            Id = new Guid("01968397-20e1-7221-aa45-68b9514b36c6"),
                            PermissionCode = 15,
                            RoleId = new Guid("01968397-20e1-768b-ba1e-75aca20fd1e0")
                        },
                        new
                        {
                            Id = new Guid("01968397-20e1-74f6-9db0-bc4dd2960510"),
                            PermissionCode = 16,
                            RoleId = new Guid("01968397-20e1-768b-ba1e-75aca20fd1e0")
                        },
                        new
                        {
                            Id = new Guid("01968397-20e1-7a80-9fa3-b23e80513292"),
                            PermissionCode = 17,
                            RoleId = new Guid("01968397-20e1-768b-ba1e-75aca20fd1e0")
                        },
                        new
                        {
                            Id = new Guid("01968397-20e1-7df6-82c2-3135354a918e"),
                            PermissionCode = 18,
                            RoleId = new Guid("01968397-20e1-768b-ba1e-75aca20fd1e0")
                        },
                        new
                        {
                            Id = new Guid("01968397-20e1-7fae-b1a7-86cee69a959c"),
                            PermissionCode = 19,
                            RoleId = new Guid("01968397-20e1-768b-ba1e-75aca20fd1e0")
                        },
                        new
                        {
                            Id = new Guid("01968397-20e1-7314-a253-c35f0ae4d117"),
                            PermissionCode = 20,
                            RoleId = new Guid("01968397-20e1-768b-ba1e-75aca20fd1e0")
                        },
                        new
                        {
                            Id = new Guid("01968397-20e1-7ea0-bb14-21dd58b3b73f"),
                            PermissionCode = 21,
                            RoleId = new Guid("01968397-20e1-768b-ba1e-75aca20fd1e0")
                        },
                        new
                        {
                            Id = new Guid("01968397-20e1-782e-b20f-fc9b67c5c167"),
                            PermissionCode = 22,
                            RoleId = new Guid("01968397-20e1-768b-ba1e-75aca20fd1e0")
                        },
                        new
                        {
                            Id = new Guid("01968397-20e1-7398-a54a-fcf8769d4be8"),
                            PermissionCode = 24,
                            RoleId = new Guid("01968397-20e1-768b-ba1e-75aca20fd1e0")
                        },
                        new
                        {
                            Id = new Guid("01968397-20e1-717b-af0e-8822f6729da2"),
                            PermissionCode = 26,
                            RoleId = new Guid("01968397-20e1-768b-ba1e-75aca20fd1e0")
                        },
                        new
                        {
                            Id = new Guid("01968397-20e1-7a66-ba32-c1fa2938b6c1"),
                            PermissionCode = 27,
                            RoleId = new Guid("01968397-20e1-768b-ba1e-75aca20fd1e0")
                        },
                        new
                        {
                            Id = new Guid("01968397-20e1-734a-bdeb-8158e83d5732"),
                            PermissionCode = 28,
                            RoleId = new Guid("01968397-20e1-768b-ba1e-75aca20fd1e0")
                        },
                        new
                        {
                            Id = new Guid("01968397-20e1-763a-8ab0-cf36a8c77ba8"),
                            PermissionCode = 1,
                            RoleId = new Guid("01968397-20e1-7549-bd8f-2783ebd4a988")
                        },
                        new
                        {
                            Id = new Guid("01968397-20e1-7fb9-a066-d14799ee0131"),
                            PermissionCode = 5,
                            RoleId = new Guid("01968397-20e1-7549-bd8f-2783ebd4a988")
                        },
                        new
                        {
                            Id = new Guid("01968397-20e1-76eb-989f-a83a04a5d558"),
                            PermissionCode = 9,
                            RoleId = new Guid("01968397-20e1-7549-bd8f-2783ebd4a988")
                        },
                        new
                        {
                            Id = new Guid("01968397-20e1-736b-bf4e-82375c3b3088"),
                            PermissionCode = 13,
                            RoleId = new Guid("01968397-20e1-7549-bd8f-2783ebd4a988")
                        },
                        new
                        {
                            Id = new Guid("01968397-20e1-73fb-ac2d-160cd970793b"),
                            PermissionCode = 17,
                            RoleId = new Guid("01968397-20e1-7549-bd8f-2783ebd4a988")
                        },
                        new
                        {
                            Id = new Guid("01968397-20e1-721f-b65c-9b2d5d2cffe5"),
                            PermissionCode = 21,
                            RoleId = new Guid("01968397-20e1-7549-bd8f-2783ebd4a988")
                        },
                        new
                        {
                            Id = new Guid("01968397-20e1-7e03-88ef-22f9bad08236"),
                            PermissionCode = 25,
                            RoleId = new Guid("01968397-20e1-7549-bd8f-2783ebd4a988")
                        });
                });

            modelBuilder.Entity("Infrastructure.Entities.Identity.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("Infrastructure.Entities.Identity.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue(new DateTime(2025, 4, 29, 22, 7, 21, 972, DateTimeKind.Utc).AddTicks(5232))
                        .HasColumnName("CreatedAt");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasColumnName("Name");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue(new DateTime(2025, 4, 29, 22, 7, 21, 974, DateTimeKind.Utc).AddTicks(3070))
                        .HasColumnName("UpdatedAt");

                    b.HasKey("Id");

                    b.ToTable("Roles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("01968397-20e1-78f5-ba61-f6d18b58e966"),
                            CreatedAt = new DateTime(2025, 4, 29, 22, 7, 21, 825, DateTimeKind.Utc).AddTicks(3257),
                            Name = "Administrator",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("01968397-20e1-768b-ba1e-75aca20fd1e0"),
                            CreatedAt = new DateTime(2025, 4, 29, 22, 7, 21, 825, DateTimeKind.Utc).AddTicks(3565),
                            Name = "Developer",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("01968397-20e1-7549-bd8f-2783ebd4a988"),
                            CreatedAt = new DateTime(2025, 4, 29, 22, 7, 21, 825, DateTimeKind.Utc).AddTicks(3568),
                            Name = "QA",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("Infrastructure.Entities.Identity.Team", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("Teams", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("01968397-20e1-7023-948b-68d5b20307f6"),
                            Name = "Admins",
                            RoleId = new Guid("01968397-20e1-78f5-ba61-f6d18b58e966")
                        },
                        new
                        {
                            Id = new Guid("01968397-20e1-7226-b60b-140d2e6e6d1c"),
                            Name = "Devs",
                            RoleId = new Guid("01968397-20e1-768b-ba1e-75aca20fd1e0")
                        },
                        new
                        {
                            Id = new Guid("01968397-20e1-72a2-91d9-3cddf518d12a"),
                            Name = "QA",
                            RoleId = new Guid("01968397-20e1-7549-bd8f-2783ebd4a988")
                        });
                });

            modelBuilder.Entity("Infrastructure.Entities.Identity.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("Id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue(new DateTime(2025, 4, 29, 22, 7, 21, 992, DateTimeKind.Utc).AddTicks(2321))
                        .HasColumnName("CreatedAt");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasColumnName("Email");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasColumnName("Name");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasColumnName("Password");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue(new DateTime(2025, 4, 29, 22, 7, 21, 992, DateTimeKind.Utc).AddTicks(3244))
                        .HasColumnName("UpdatedAt");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("EmailIndex");

                    b.ToTable("Users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("01968397-20e1-75ce-9292-2b1010dcd92c"),
                            CreatedAt = new DateTime(2025, 4, 29, 22, 7, 21, 826, DateTimeKind.Utc).AddTicks(584),
                            Email = "admin@admin.com",
                            Name = "admin",
                            Password = "z3+rEL+8qBOywW3oL7ibQ1XzZeYenTfhqoQBDICpKUqqHiWg",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("01968397-20ed-73e1-905f-dc138a2c0bde"),
                            CreatedAt = new DateTime(2025, 4, 29, 22, 7, 21, 837, DateTimeKind.Utc).AddTicks(8537),
                            Email = "dev@dev.com",
                            Name = "dev",
                            Password = "6kQsexQTUZFZhmDTmCjL/y8D3SXPsULBd81ivyKZdVNbrnzz",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("01968397-20f3-7ab4-b0b3-649133fac306"),
                            CreatedAt = new DateTime(2025, 4, 29, 22, 7, 21, 843, DateTimeKind.Utc).AddTicks(9246),
                            Email = "qa@qa.com",
                            Name = "qa",
                            Password = "GKgD3xbni671kItljE6VOEhjuprtOIHBIRdMRPd0OQBZABzI",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("Infrastructure.Entities.Platform", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Address")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("AgentVersion")
                        .HasColumnType("TEXT");

                    b.Property<string>("Architecture")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<long>("Containers")
                        .HasColumnType("INTEGER");

                    b.Property<long>("ContainersPaused")
                        .HasColumnType("INTEGER");

                    b.Property<long>("ContainersRunning")
                        .HasColumnType("INTEGER");

                    b.Property<long>("ContainersStopped")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DaemonId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Driver")
                        .HasColumnType("TEXT");

                    b.Property<long>("Images")
                        .HasColumnType("INTEGER");

                    b.Property<long>("MemTotal")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<long>("Ncpu")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NetworksCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OperatingSystem")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("OsType")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("OsVersion")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("ServerVersion")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("VolumesCount")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Address")
                        .IsUnique()
                        .HasDatabaseName("AddressIndex");

                    b.ToTable("Platforms", (string)null);
                });

            modelBuilder.Entity("Infrastructure.Entities.PlatformStat", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<double>("CpuUsage")
                        .HasColumnType("REAL");

                    b.Property<long>("Created")
                        .HasColumnType("INTEGER");

                    b.Property<double>("MemoryUsage")
                        .HasColumnType("REAL");

                    b.Property<Guid>("PlatformId")
                        .HasColumnType("TEXT");

                    b.Property<double>("RxBytes")
                        .HasColumnType("REAL");

                    b.Property<double>("TxBytes")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("Created")
                        .IsUnique();

                    b.HasIndex("PlatformId");

                    b.ToTable("PlatformStats", (string)null);
                });

            modelBuilder.Entity("Infrastructure.Entities.Registry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Configuration")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Registries", (string)null);
                });

            modelBuilder.Entity("Infrastructure.Entities.SwarmInfo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("ControlAvailable")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Error")
                        .HasColumnType("TEXT");

                    b.Property<string>("LocalNodeState")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<long>("Managers")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NodeAddr")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("NodeID")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<long>("Nodes")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("PlatformId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PlatformId")
                        .IsUnique();

                    b.ToTable("SwarmsInfo", (string)null);
                });

            modelBuilder.Entity("Infrastructure.Entities.SwarmPeer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Addr")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("NodeID")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SwarmInfoId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SwarmInfoId");

                    b.ToTable("SwarmsPeer", (string)null);
                });

            modelBuilder.Entity("Infrastructure.EntityFramework.JoiningTables.UserTeam", b =>
                {
                    b.Property<Guid>("TeamId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("TeamId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("UsersTeams");

                    b.HasData(
                        new
                        {
                            TeamId = new Guid("01968397-20e1-7023-948b-68d5b20307f6"),
                            UserId = new Guid("01968397-20e1-75ce-9292-2b1010dcd92c")
                        },
                        new
                        {
                            TeamId = new Guid("01968397-20e1-7226-b60b-140d2e6e6d1c"),
                            UserId = new Guid("01968397-20ed-73e1-905f-dc138a2c0bde")
                        },
                        new
                        {
                            TeamId = new Guid("01968397-20e1-72a2-91d9-3cddf518d12a"),
                            UserId = new Guid("01968397-20f3-7ab4-b0b3-649133fac306")
                        });
                });

            modelBuilder.Entity("Infrastructure.Entities.ContainerInfo", b =>
                {
                    b.HasOne("Infrastructure.Entities.Platform", "Platform")
                        .WithMany("ContainersInfo")
                        .HasForeignKey("PlatformId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsMany("Infrastructure.Entities.ContainerPort", "Ports", b1 =>
                        {
                            b1.Property<Guid>("ContainerInfoId")
                                .HasColumnType("TEXT");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAddOrUpdate()
                                .HasColumnType("INTEGER");

                            b1.Property<string>("IP")
                                .HasColumnType("TEXT");

                            b1.Property<int?>("PrivatePort")
                                .HasColumnType("INTEGER");

                            b1.Property<int?>("PublicPort")
                                .HasColumnType("INTEGER");

                            b1.HasKey("ContainerInfoId", "__synthesizedOrdinal");

                            b1.ToTable("ContainersInfo");

                            b1.ToJson("Ports");

                            b1.WithOwner()
                                .HasForeignKey("ContainerInfoId");
                        });

                    b.Navigation("Platform");

                    b.Navigation("Ports");
                });

            modelBuilder.Entity("Infrastructure.Entities.ContainerStat", b =>
                {
                    b.HasOne("Infrastructure.Entities.ContainerInfo", null)
                        .WithMany("Stats")
                        .HasForeignKey("ContainerInfoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Infrastructure.Entities.Identity.Permission", b =>
                {
                    b.HasOne("Infrastructure.Entities.Identity.Role", null)
                        .WithMany("Permissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Infrastructure.Entities.Identity.RefreshToken", b =>
                {
                    b.HasOne("Infrastructure.Entities.Identity.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Infrastructure.Entities.Identity.Team", b =>
                {
                    b.HasOne("Infrastructure.Entities.Identity.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Infrastructure.Entities.PlatformStat", b =>
                {
                    b.HasOne("Infrastructure.Entities.Platform", null)
                        .WithMany("Stats")
                        .HasForeignKey("PlatformId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Infrastructure.Entities.SwarmInfo", b =>
                {
                    b.HasOne("Infrastructure.Entities.Platform", "Platform")
                        .WithOne("SwarmInfo")
                        .HasForeignKey("Infrastructure.Entities.SwarmInfo", "PlatformId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Platform");
                });

            modelBuilder.Entity("Infrastructure.Entities.SwarmPeer", b =>
                {
                    b.HasOne("Infrastructure.Entities.SwarmInfo", "SwarmInfo")
                        .WithMany("RemoteManagers")
                        .HasForeignKey("SwarmInfoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SwarmInfo");
                });

            modelBuilder.Entity("Infrastructure.EntityFramework.JoiningTables.UserTeam", b =>
                {
                    b.HasOne("Infrastructure.Entities.Identity.Team", null)
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Infrastructure.Entities.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Infrastructure.Entities.ContainerInfo", b =>
                {
                    b.Navigation("Stats");
                });

            modelBuilder.Entity("Infrastructure.Entities.Identity.Role", b =>
                {
                    b.Navigation("Permissions");
                });

            modelBuilder.Entity("Infrastructure.Entities.Identity.User", b =>
                {
                    b.Navigation("RefreshTokens");
                });

            modelBuilder.Entity("Infrastructure.Entities.Platform", b =>
                {
                    b.Navigation("ContainersInfo");

                    b.Navigation("Stats");

                    b.Navigation("SwarmInfo");
                });

            modelBuilder.Entity("Infrastructure.Entities.SwarmInfo", b =>
                {
                    b.Navigation("RemoteManagers");
                });
#pragma warning restore 612, 618
        }
    }
}
