[package]
name = "citadel-builds"
version = "0.0.0"
edition.workspace = true
rust-version.workspace = true
publish = false

[dependencies]
citadel-tags = { path = "../tags" }
citadel-primitives = { path = "../primitives" }
citadel-licensing = { path = "../licensing" }
citadel-activities = { path = "../activities" }
chrono.workspace = true
citadel-alerts = { path = "../alerts" }
futures-util.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tokio.workspace = true
tokio-util.workspace = true
tracing.workspace = true
uuid.workspace = true
url.workspace = true
zeroize.workspace = true

[lints]
workspace = true
