<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<RootNamespace>Tests.Common</RootNamespace>
		<PublishTrimmed>false</PublishTrimmed>
		<PublishAot>false</PublishAot>
	</PropertyGroup>

	<ItemGroup>
		<Compile Remove="VerifyChecksTests.cs" />
		<PackageReference Include="Bogus" />
		<PackageReference Include="Microsoft.NET.Test.Sdk" />
		<PackageReference Include="Moq" />
		<PackageReference Include="Verify.XunitV3" />
		<PackageReference Include="xunit.v3" />
		<PackageReference Include="xunit.runner.visualstudio" >
		  <PrivateAssets>all</PrivateAssets>
		  <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\src\Citadel.Application\Citadel.Application.csproj" />
		<ProjectReference Include="..\..\src\Citadel.Contracts\src\Citadel.Hosting.Common\Citadel.Hosting.Common.csproj" />
		<ProjectReference Include="..\..\src\Citadel.Contracts\src\Citadel.Hosting\Citadel.Hosting.csproj" />
		<ProjectReference Include="..\..\src\Citadel.Contracts\src\Citadel.SourceGen\Citadel.SourceGen.csproj" />
		<ProjectReference Include="..\..\src\Citadel.Infrastructure\Citadel.Infrastructure.csproj" />
	</ItemGroup>

	<ItemGroup>
	  <Content Include="xunit.runner.json">
	    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	  </Content>
	</ItemGroup>

</Project>
