[package]
name = "citadel-processes"
version = "0.0.0"
edition.workspace = true
rust-version.workspace = true
publish = false
[dependencies]
citadel-execution = { path = "../../features/execution" }
futures-util.workspace = true
tokio.workspace = true
tokio-util.workspace = true

[lints]
workspace = true
