use chrono::{DateTime, Utc};
use citadel_domain::ActorId;
use futures_util::future::BoxFuture;
use serde::{Deserialize, Serialize};
use serde_json::{Value, json};
use std::sync::Arc;
use uuid::Uuid;
use zeroize::Zeroizing;
mod model;
pub use model::{GitAccount, GitAuthConfiguration, GitAuthType, GitTransport, StoredGitAccount};
mod commands;
pub use commands::{CreateGitAccount, UpdateGitAccount};
mod read_models;
pub use read_models::GitAccountConfiguration;
mod error;
pub use error::GitAccountError;
mod runtime;
pub use runtime::GitCredentialProtector;
mod repository;
pub use repository::GitAccountRepository;
mod service;
pub use service::GitAccountService;
mod validation;
use validation::{validate_configuration, validate_domain, validate_name};
