namespace Infrastructure.Persistence.Dtos;

internal sealed record BuildProjectDto(
    Guid Id,
    string Name,
    string NormalizedName,
    string? Description,
    bool Enabled,
    Guid GitRepositoryId,
    string Branch,
    string ContextPath,
    string DockerfilePath,
    string? Target,
    string BuildArgs,
    string BuildSecrets,
    Guid PlatformId,
    Guid RegistryId,
    string ImageRepository,
    string TagTemplates,
    string? Webhook,
    int TimeoutSeconds,
    int RetentionRunCount,
    Guid? CurrentRunId,
    string? ControlState,
    long? ControlStartedAt,
    Guid CreatedByActorId,
    DateTime CreatedAt,
    DateTime UpdatedAt,
    DateTime? ArchivedAt,
    long RowVersion,
    string? TagsJson = null)
{
    public BuildProjectDto()
        : this(
            Guid.Empty,
            string.Empty,
            string.Empty,
            null,
            false,
            Guid.Empty,
            string.Empty,
            string.Empty,
            string.Empty,
            null,
            "[]",
            "[]",
            Guid.Empty,
            Guid.Empty,
            string.Empty,
            "[]",
            null,
            0,
            0,
            null,
            null,
            null,
            Guid.Empty,
            DateTime.MinValue,
            DateTime.MinValue,
            null,
            0)
    {
    }
}

internal sealed record BuildRunDto(
    Guid Id,
    Guid BuildProjectId,
    string ProjectNameSnapshot,
    Guid GitRepositoryId,
    string GitRepositoryNameSnapshot,
    string Branch,
    string? ResolvedCommitSha,
    string ContextPath,
    string DockerfilePath,
    string? Target,
    string BuildArgsSnapshot,
    string BuildSecretIdsSnapshot,
    string PlatformSnapshot,
    string RegistrySnapshot,
    string ImageRepository,
    string TagTemplatesSnapshot,
    string ImageReferences,
    string Trigger,
    Guid? TriggerSourceId,
    string Status,
    string? ImageDigest,
    int TimeoutSeconds,
    DateTime QueuedAt,
    DateTime? StartedAt,
    DateTime? CompletedAt,
    int? ExitCode,
    string? ErrorCode,
    string? ErrorMessage,
    Guid TriggeredByActorId)
{
    public BuildRunDto()
        : this(
            Guid.Empty,
            Guid.Empty,
            string.Empty,
            Guid.Empty,
            string.Empty,
            string.Empty,
            null,
            string.Empty,
            string.Empty,
            null,
            "[]",
            "[]",
            "{}",
            "{}",
            string.Empty,
            "[]",
            "[]",
            string.Empty,
            null,
            string.Empty,
            null,
            0,
            DateTime.MinValue,
            null,
            null,
            null,
            null,
            null,
            Guid.Empty)
    {
    }
}

internal sealed record BuildRunLogDto(
    Guid Id,
    Guid BuildRunId,
    DateTime CreatedAt,
    string Stream,
    string Message)
{
    public BuildRunLogDto()
        : this(Guid.Empty, Guid.Empty, DateTime.MinValue, string.Empty, string.Empty)
    {
    }
}

internal sealed record BuildProjectParameters(
    Guid Id,
    string Name,
    string NormalizedName,
    string? Description,
    bool Enabled,
    Guid GitRepositoryId,
    string Branch,
    string ContextPath,
    string DockerfilePath,
    string? Target,
    string BuildArgs,
    string BuildSecrets,
    Guid PlatformId,
    Guid RegistryId,
    string ImageRepository,
    string TagTemplates,
    string? Webhook,
    int TimeoutSeconds,
    int RetentionRunCount,
    Guid? CurrentRunId,
    string ControlState,
    long? ControlStartedAt,
    DateTime UpdatedAt,
    DateTime? ArchivedAt,
    long RowVersion);

internal sealed record BuildRunParameters(
    Guid Id,
    Guid BuildProjectId,
    string ProjectNameSnapshot,
    Guid GitRepositoryId,
    string GitRepositoryNameSnapshot,
    string Branch,
    string? ResolvedCommitSha,
    string ContextPath,
    string DockerfilePath,
    string? Target,
    string BuildArgsSnapshot,
    string BuildSecretIdsSnapshot,
    string PlatformSnapshot,
    string RegistrySnapshot,
    string ImageRepository,
    string TagTemplatesSnapshot,
    string ImageReferences,
    string Trigger,
    Guid? TriggerSourceId,
    string Status,
    string? ImageDigest,
    int TimeoutSeconds,
    DateTime QueuedAt,
    DateTime? StartedAt,
    DateTime? CompletedAt,
    int? ExitCode,
    string? ErrorCode,
    string? ErrorMessage,
    Guid TriggeredByActorId);
