namespace Infrastructure.Persistence.Dtos;

internal sealed record EdgeAgentEnrollmentDto(
    Guid Id,
    Guid PlatformId,
    string TokenHash,
    DateTime ExpiresAtUtc,
    DateTime? UsedAtUtc,
    DateTime? RevokedAtUtc,
    Guid CreatedByActorId,
    DateTime CreatedAtUtc);

internal sealed record EdgeAgentBindingDto(
    Guid Id,
    Guid PlatformId,
    Guid AgentId,
    string AgentPublicKey,
    string AgentFingerprint,
    string ConnectionStatus,
    DateTime? LastConnectedAtUtc,
    DateTime? LastDisconnectedAtUtc,
    DateTime? LastHeartbeatAtUtc,
    string? LastSeenVersion,
    string? LastSeenHostname,
    string? CapabilitiesJson,
    int ProtocolVersion,
    DateTime? RevokedAtUtc,
    DateTime CreatedAtUtc,
    DateTime UpdatedAtUtc);

internal sealed record EdgeAgentPlatformStateDto(
    Guid PlatformId,
    string PlatformName,
    string PlatformAddress,
    int PlatformNetworkCount,
    int PlatformVolumeCount,
    long PlatformImageCount,
    long PlatformCpuCount,
    long PlatformMemTotal,
    string PlatformStatus,
    string PlatformConnectorType,
    string PlatformDescriptor,
    string? PlatformServerVersion,
    string? PlatformAgentVersion,
    string? PlatformDescription,
    Guid? BindingId,
    Guid? BindingPlatformId,
    Guid? BindingAgentId,
    string? BindingAgentPublicKey,
    string? BindingAgentFingerprint,
    string? BindingConnectionStatus,
    DateTime? BindingLastConnectedAtUtc,
    DateTime? BindingLastDisconnectedAtUtc,
    DateTime? BindingLastHeartbeatAtUtc,
    string? BindingLastSeenVersion,
    string? BindingLastSeenHostname,
    string? BindingCapabilitiesJson,
    int? BindingProtocolVersion,
    DateTime? BindingRevokedAtUtc,
    DateTime? BindingCreatedAtUtc,
    DateTime? BindingUpdatedAtUtc);
