<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
	<RootNamespace>Tests.Unit</RootNamespace>
	<PublishTrimmed>false</PublishTrimmed>
	<OutputType>exe</OutputType>
	<PublishAot>false</PublishAot>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="..\Citadel.Tests.Common\VerifyChecksTests.cs" Link="VerifyChecksTests.cs" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="..\Citadel.Tests.Common\xunit.runner.json" Link="xunit.runner.json" />
  </ItemGroup>

	<ItemGroup>
		<Using Include="Xunit" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Citadel.Tests.Common\Citadel.Tests.Common.csproj" />
	</ItemGroup>

</Project>
