<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
	<ImplicitUsings>enable</ImplicitUsings>
	<RootNamespace>Application</RootNamespace>
	<EmitCompilerGeneratedFiles>true</EmitCompilerGeneratedFiles>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="Features.Images\default.docker.images.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
	<PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="9.0.4" />
	<PackageReference Include="Mediator.SourceGenerator" Version="3.0.0-preview.64">
		<PrivateAssets>all</PrivateAssets>
		<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
	</PackageReference>
  </ItemGroup>

  <ItemGroup>
	 <ProjectReference Include="..\Citadel.Infrastructure\Citadel.Infrastructure.csproj" />
	 <ProjectReference Include="..\Citadel.Contracts\Citadel.SourceGen\Citadel.SourceGen.csproj"
					   OutputItemType="Analyzer" ReferenceOutputAssembly="false" PrivateAssets="all"/>
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Features.Platforms\Models\" />
  </ItemGroup>

</Project>
