<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <ImplicitUsings>enable</ImplicitUsings>
	<RootNamespace>Infrastructure</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
	<PackageReference Include="Dapper" Version="2.1.66" />
	<PackageReference Include="FluentMigrator" Version="7.1.0" />
	<PackageReference Include="Refit" Version="8.0.0" />
	<PackageReference Include="Refit.HttpClientFactory" Version="8.0.0" />
	<PackageReference Include="dbup-sqlite" Version="6.0.1" />
	<PackageReference Include="SQLitePCLRaw.bundle_e_sqlite3" Version="2.1.11" />
    <PackageReference Include="Microsoft.IdentityModel.JsonWebTokens" Version="8.12.1" />
  </ItemGroup>

  <ItemGroup>
	  <ProjectReference Include="..\Citadel.Contracts\Citadel.Hosting.DockerClient\Citadel.Hosting.DockerClient.csproj" />
	  <ProjectReference Include="..\Citadel.Domain\Citadel.Domain.csproj" />
  </ItemGroup>

	<ItemGroup>
		<EmbeddedResource Include="Scripts\*.sql" /> <!--for dbup-->
	</ItemGroup>

   <ItemGroup>
	   <PackageReference Include="Grpc.AspNetCore" Version="2.71.0" />
	   <Protobuf Include="..\Citadel.Contracts\Citadel.Hosting.DockerClient\Protos\container_service.proto" GrpcServices="Client" Link="Protos\container_service.proto" />
	   <Protobuf Include="..\Citadel.Contracts\Citadel.Hosting.DockerClient\Protos\image_service.proto" GrpcServices="Client" Link="Protos\image_service.proto" />
	   <Protobuf Include="..\Citadel.Contracts\Citadel.Hosting.DockerClient\Protos\platform_service.proto" GrpcServices="Client" Link="Protos\platform_service.proto" />
	   <Protobuf Include="..\Citadel.Contracts\Citadel.Hosting.DockerClient\Protos\network_service.proto" GrpcServices="Client" Link="Protos\network_service.proto" />
	   <Protobuf Include="..\Citadel.Contracts\Citadel.Hosting.DockerClient\Protos\volume_service.proto" GrpcServices="Client" Link="Protos\volume_service.proto" />

	   <Protobuf Include="..\Citadel.Contracts\Citadel.Hosting.DockerClient\Protos\Common\platform_model.proto" GrpcServices="None" Link="Protos\Common\platform_model.proto" />
	   <Protobuf Include="..\Citadel.Contracts\Citadel.Hosting.DockerClient\Protos\Common\container_model.proto" GrpcServices="None" Link="Protos\Common\container_model.proto" />
   </ItemGroup>

   <ItemGroup>
     <Folder Include="Scripts\" />
   </ItemGroup>

</Project>
