<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <ImplicitUsings>enable</ImplicitUsings>
	<RootNamespace>Infrastructure</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
	<PackageReference Include="dbup-sqlite" Version="6.0.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="9.0.4" />
	<PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.4">
	  <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
	</PackageReference>
    <PackageReference Include="Microsoft.IdentityModel.JsonWebTokens" Version="8.9.0" />
  </ItemGroup>

  <ItemGroup>
	<EmbeddedResource Include="Migrations\*.sql" /> <!--for dbup-->
  </ItemGroup>
	
  <ItemGroup>
	  <ProjectReference Include="..\Citadel.Contracts\Citadel.Hosting.Common\Citadel.Hosting.Common.csproj" />
  </ItemGroup>

   <ItemGroup>
	   <PackageReference Include="Grpc.AspNetCore" Version="2.71.0" />
	   <Protobuf Include="..\Citadel.Contracts\Citadel.Hosting.Common\Protos\agent.containers.proto" GrpcServices="Client" Link="Protos\agent.containers.proto" />
	   <Protobuf Include="..\Citadel.Contracts\Citadel.Hosting.Common\Protos\agent.images.proto" GrpcServices="Client" Link="Protos\agent.images.proto" />
	   <Protobuf Include="..\Citadel.Contracts\Citadel.Hosting.Common\Protos\agent.platform.proto" GrpcServices="Client" Link="Protos\agent.platform.proto" />
	   <Protobuf Include="..\Citadel.Contracts\Citadel.Hosting.Common\Protos\agent.networks.proto" GrpcServices="Client" Link="Protos\agent.networks.proto" />
	   <Protobuf Include="..\Citadel.Contracts\Citadel.Hosting.Common\Protos\agent.volumes.proto" GrpcServices="Client" Link="Protos\agent.volumes.proto" />

	   <Protobuf Include="..\Citadel.Contracts\Citadel.Hosting.Common\Protos\Common\platforms.proto" GrpcServices="None" Link="Protos\Common\platforms.proto" />
	   <Protobuf Include="..\Citadel.Contracts\Citadel.Hosting.Common\Protos\Common\containers.proto" GrpcServices="None" Link="Protos\Common\containers.proto" />
   </ItemGroup>
	

</Project>
