import {
  ResourceCapabilitiesView,
  PlatformView,
  PlatformStatus,
  PlatformConnectorType,
  ManagedSwarmServiceView,
  SwarmServiceHealth,
  SwarmServiceSynchronizationState,
  AutoUpdateStatus,
  SwarmTaskView,
  PlatformType,
  ResourceControlState,
  StackReleaseStatus,
  StackSource,
  StackDriftMode,
  StackUpdateState,
  StackView,
} from '@/api/generated/api.types';

export const createResourceCapabilities = (overrides: Partial<ResourceCapabilitiesView> = {}): ResourceCapabilitiesView => ({
  canRead: true,
  canWrite: true,
  canExecute: true,
  ...overrides,
});

export const createStack = (overrides: Partial<StackView> = {}): StackView => ({
  capabilities: null,
  id: '00000000-0000-0000-0000-000000000001',
  name: 'api',
  latestActivityView: null,
  platformName: null,
  platformStatus: PlatformStatus.Online,
  resourceBindings: null,
  rowVersion: 1,
  source: null,
  spec: null,
  version: null,
  description: null,
  stackSource: StackSource.WebEditor,
  stackUpdateState: {
    $type: 'WebEditor',
    recreateStackOnNewImageState: { autoUpdateStates: [] },
  } as StackUpdateState,
  driftPolicy: {
    mode: StackDriftMode.Disabled,
    alertOnDrift: false,
    markDegraded: false,
    autoStartStoppedContainers: false,
    autoResumePausedContainers: false,
    removeExtraContainers: false,
  },
  status: StackReleaseStatus.Healthy,
  createdAt: '2026-01-01T00:00:00.000Z',
  createdByActorId: '00000000-0000-0000-0000-000000000010',
  controlState: ResourceControlState.Idle,
  currentStackReleaseId: '00000000-0000-0000-0000-000000000100',
  platformType: PlatformType.Docker,
  platformId: '00000000-0000-0000-0000-000000000200',
  tags: [],
  ...overrides,
});

export const createPlatform = (overrides: Partial<PlatformView> = {}): PlatformView => ({
  capabilities: null,
  id: 'platform-1',
  name: 'Platform',
  description: null,
  address: 'unix:///var/run/docker.sock',
  networkCount: 0,
  volumeCount: 0,
  imageCount: 0,
  cpuCount: 1,
  memTotal: 1024,
  agentVersion: null,
  serverVersion: '29.0.0',
  type: PlatformType.Docker,
  status: PlatformStatus.Online,
  connectorType: PlatformConnectorType.Local,
  deploymentCount: 0,
  stackCount: 0,
  deploymentStatusCounts: {
    total: 0,
    healthy: 0,
    degraded: 0,
    failed: 0,
    stopped: 0,
    paused: 0,
    inProgress: 0,
    unknown: 0,
  },
  stackStatusCounts: { total: 0, healthy: 0, degraded: 0, failed: 0, stopped: 0, paused: 0, inProgress: 0, unknown: 0 },
  swarmServiceStatusCounts: {
    total: 0,
    healthy: 0,
    degraded: 0,
    failed: 0,
    stopped: 0,
    paused: 0,
    inProgress: 0,
    unknown: 0,
  },
  stats: [],
  platformDescriptor: null,
  clusterId: null,
  pruneHistoricalSwarmTaskContainers: false,
  tags: [],
  ...overrides,
});

export const createManagedSwarmService = (
  overrides: Partial<ManagedSwarmServiceView> = {},
): ManagedSwarmServiceView => ({
  capabilities: null,
  id: 'service-1',
  platformId: 'platform-1',
  name: 'web',
  description: null,
  dockerName: 'web',
  dockerServiceId: null,
  spec: { image: { $type: 'External', registryId: 'registry-1', imageTag: 'nginx:latest' } },
  health: SwarmServiceHealth.Unknown,
  synchronizationState: SwarmServiceSynchronizationState.NeverApplied,
  controlState: ResourceControlState.Idle,
  autoUpdateState: {
    lastCheckedAt: '2026-09-28T00:00:00Z',
    status: AutoUpdateStatus.Unknown,
    currentDigest: null,
    remoteDigest: null,
    lastError: null,
  },
  appliedImageDigest: null,
  hasPendingDesiredChanges: false,
  hasRuntimeDrift: false,
  rowVersion: 1,
  createdAt: '2026-09-28T00:00:00Z',
  updatedAt: '2026-09-28T00:00:00Z',
  platformName: 'Swarm',
  platformStatus: PlatformStatus.Online,
  runningTaskCount: null,
  desiredTaskCount: null,
  updateState: null,
  updateMessage: null,
  currentOperation: null,
  tags: [],
  tasks: [],
  ...overrides,
});

export const createSwarmTask = (overrides: Partial<SwarmTaskView> = {}): SwarmTaskView => ({
  capabilities: null,
  id: 'task-1',
  versionIndex: 1,
  name: 'web.1',
  serviceId: 'service-1',
  serviceName: 'web',
  slot: 1,
  nodeId: 'node-1',
  nodeHostname: 'manager-1',
  desiredState: 'running',
  state: 'running',
  statusMessage: null,
  error: null,
  image: 'nginx:latest',
  ports: [],
  statusTimestamp: null,
  createdAt: null,
  updatedAt: null,
  observedAt: '2026-09-28T00:00:00Z',
  isStale: false,
  ...overrides,
});
