#![forbid(unsafe_code)]

pub mod activity_store;
pub mod agent;
mod agent_execution;
pub mod alert_store;
pub mod automation_store;
pub mod automation_token;
pub mod backup_authorization;
pub mod backup_executor;
pub mod backup_source_planner;
pub mod backup_store;
pub mod build_executor;
pub mod build_store;
pub mod citadel_system_backup;
mod container_ports;
pub mod container_stats_store;
pub mod crypto;
pub mod deployment_bindings;
pub mod deployment_runtime;
pub mod deployment_store;
pub mod docker;
pub mod edge;
pub mod git_account_store;
pub mod git_repository_execution_store;
pub mod identity_store;
pub mod inventory_projection_store;
pub mod license;
mod local_docker_target;
pub mod lookup_store;
pub mod mfa;
pub mod oidc_protocol;
pub mod oidc_store;
pub mod platform_read_store;
pub mod platform_registration;
mod postgres;
pub mod postgres_runtime;
pub mod profile_store;
pub mod resource_metadata_store;
mod resource_tags;
pub mod role_store;
pub mod secret_value_resolver;
pub mod service_account_store;
pub mod stack_bindings;
pub mod stack_build_images;
pub mod stack_runtime;
pub mod stack_source_materializer;
pub mod stack_store;
pub mod statistics_read_store;
pub mod swarm_service_bindings;
pub mod swarm_service_runtime;
pub mod swarm_service_store;
pub mod team_store;
pub mod user_store;

pub use postgres::PostgresAuthorizedPlatformReader;
