using Citadel.Agent.Common.V1;

namespace WebApi.Routes.Endpoints.Resources.Containers;

public sealed record ContainerInspectView(
    string Id,
    string Created,
    string Path,
    ICollection<string> Args,
    ContainerState State,
    string Image,
    string ResolvConfPath,
    string HostnamePath,
    string HostsPath,
    string LogPath,
    string Name,
    int? RestartCount,
    string Driver,
    string Platform,
    string MountLabel,
    string ProcessLabel,
    string AppArmorProfile,
    ICollection<string> ExecIDs,
    HostConfig HostConfig,
    GraphDriverData GraphDriver,
    long? SizeRw,
    long? SizeRootFs,
    ICollection<MountPoint> Mounts,
    ContainerConfig Config,
    NetworkSettingsView NetworkSettings)
{
    internal static ContainerInspectView Map(InspectContainerResponse containerInspect) => new(
            Id: containerInspect.Id,
            Created: containerInspect.Created,
            Path: containerInspect.Path,
            Args: [.. containerInspect.Args],
            State: containerInspect.State,
            Image: containerInspect.Image,
            ResolvConfPath: containerInspect.ResolvConfPath,
            HostnamePath: containerInspect.HostnamePath,
            HostsPath: containerInspect.HostsPath,
            LogPath: containerInspect.LogPath,
            Name: containerInspect.Name,
            RestartCount: containerInspect.RestartCount,
            Driver: containerInspect.Driver,
            Platform: containerInspect.Platform,
            MountLabel: containerInspect.MountLabel,
            ProcessLabel: containerInspect.ProcessLabel,
            AppArmorProfile: containerInspect.AppArmorProfile,
            ExecIDs: [.. containerInspect.ExecIDs],
            HostConfig: containerInspect.HostConfig,
            GraphDriver: containerInspect.GraphDriver,
            SizeRw: containerInspect.SizeRw,
            SizeRootFs: containerInspect.SizeRootFs,
            Mounts: [.. containerInspect.Mounts],
            Config: containerInspect.Config,
            NetworkSettings: containerInspect.NetworkSettings.Map());
}
